hopshadoop/hopsworks

- pom.xml
- src/main/java/se/kth/bbc/security/ua/model/BBCGroup.java
- src/main/java/se/kth/hopsworks/filters/RequestAuthFilter.java
- src/main/java/se/kth/hopsworks/user/model/Users.java
- src/main/java/se/kth/hopsworks/zeppelin/notebook/Notebook.java
- src/main/java/se/kth/hopsworks/zeppelin/notebook/repo/FSNotebookRepo.java
- src/main/java/se/kth/hopsworks/zeppelin/rest/InterpreterDTO.java
- src/main/java/se/kth/hopsworks/zeppelin/rest/InterpreterRestApi.java
- src/main/java/se/kth/hopsworks/zeppelin/rest/NotebookRestApi.java
- src/main/java/se/kth/hopsworks/zeppelin/server/AppScriptServlet.java
- src/main/java/se/kth/hopsworks/zeppelin/server/ReleaseZeppelinResources.java
- src/main/java/se/kth/hopsworks/zeppelin/server/ZeppelinSingleton.java
- src/main/java/se/kth/hopsworks/zeppelin/socket/NotebookServer.java
- src/main/java/se/kth/hopsworks/zeppelin/socket/ZeppelinEndpointConfig.java
- src/main/java/se/kth/hopsworks/zeppelin/util/ZeppelinResource.java
- src/main/java/se/kth/rest/application/config/ApplicationConfig.java
- src/main/resources/zeppelinConf/zeppelin-site.xml
- yo/app/index.html
- yo/app/scripts/app.js
- yo/app/scripts/controllers/project.js
- yo/app/scripts/controllers/zeppelinCtrl.js
- yo/app/scripts/directives/switch.js
- yo/app/scripts/services/RequestInterceptorService.js
- yo/app/scripts/services/ZeppelinService.js
- yo/app/scripts/util.js
- yo/app/styles/style.css
- yo/app/views/zeppelinDashboard.html
- yo/bower.json
- yo/test/karma.conf.js
1.  Show notebooks in different category 
* project specific and
* tutorial
2.  Start and stop interpreters - needs bash file that tests if a process is alive to be added to                                                                                                      /srv/zeppelin/bin 
3.  Close all open interpreters on undeploy.
4.  Change localhost to location in the front-end to support access via ip address.
5.   Changed zeppelin dependency from 0.5.1-incubating-SNAPSHOT to 0.5.0-incubating b/c 0.5.0-incubating is now in apache repo.
Problem
When starting an interpreter a temporary notebook is created, this notebook can some times end up in the project even if it is deleted after star-up is completed.
> Zeppelin dashboard

- src/main/java/se/kth/hopsworks/hdfsUsers/controller/HdfsUsersController.java
This is only a temporary fix. When yarn doAs works this wont be needed.
> fixes, iss_#229

- hopsworks-api/pom.xml
- hopsworks-api/src/main/java/com/predic8/membrane/servlet/embedded/HopsRouter.java
- hopsworks-api/src/main/java/com/predic8/membrane/servlet/embedded/HopsServletHandler.java
- hopsworks-api/src/main/java/com/predic8/membrane/servlet/embedded/MembraneServlet.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/agent/AgentResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/JupyterService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/AsyncSystemCommandExecutor.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Ip.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/LocalhostServices.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
It only worked for localhost before.
Now it works for remote hosts (hope it still works for localhost :)) 
There was another bug with Jackson dependencies being pull in from ServiceProxy. Now they are 'provided' scope and Payara provides them.
https://hopshadoop.atlassian.net/browse/HOPSWORKS-89
> Jupyter webproxy fix ( https://hopshadoop.atlassian.net/browse/HOPSWORKS-89 )

- hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/JupyterService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/LivyService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/rest/InterpreterRestApi.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/rest/InterpreterService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/rest/NotebookRestApi.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/socket/NotebookServer.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/util/LivyMsg.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/util/ZeppelinResource.java
- hopsworks-common/src/main/resources/io/hops/jupyter/config_template.json
- hopsworks-common/src/main/resources/io/hops/zeppelin/interpreter_template.json
- hopsworks-common/src/main/resources/io/hops/zeppelin/zeppelin_site_template.xml
- hopsworks-web/yo/app/navProject.html
- hopsworks-web/yo/app/scripts/controllers/project.js
- hopsworks-web/yo/app/scripts/controllers/zeppelinCtrl.js
- hopsworks-web/yo/app/views/zeppelinDashboard.html
- Remove jupyter livy sessions from zeppelin dashboard
- Ask the user to enable anaconda when going to zeppelin dashboard
- Persist interpreter.json to database when creating notebook and setting default for a notebook
> Hopsworks 151

- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkYarnRunnerBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
[HOPSWORKS-168] This PR sets the environment variables for TFoS executors launched in Job UI.
> HOPSWORKS-168 Set environment variables for TFoS submitted in Job UI

- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkYarnRunnerBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
HOPSWORKS-174 Fix bug where setting PATH for executor and appmaster crashes containers on startup. After this change TFoS using GPUs is expected to work through the Job UI.
> HOPSWORKS-174 Fix bug where setting PATH for executor and appmaster crashes containers on startup.

- hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/JobService.java
- hopsworks-common/pom.xml
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnExecutionFinalizer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnLogUtil.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnMonitor.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
check that the log aggregation is finished for the jobs killed during the project removal, before to remove the users from HDFS.
This reduce the risk of having users being put back in HDFS by the log aggregation process after the project removal. It would be better to check for all the applications belonging to the project users, but the resource manager does not recover the log aggregation status, this result in the impossibility to know if we should wait for log aggregation or not for job that run before a resource manager restart.
Need Hop 2.8.2
> [HOPSWORKS-127] 

- hopsworks-common/src/main/resources/io/hops/jupyter/config_template.json
HOPSWORKS-227 Spark executor should not export CUDA_VISIBLE_DEVICES
> HOPSWORKS-227 Spark executor should not export CUDA_VISIBLE_DEVICES

- hopsworks-web/yo/app/scripts/controllers/clusterUtilisationCtrl.js
The current GPU utilization calculation is off by a factor of 100
> HOPSWORKS-193 Fix GPU utilization bar

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfig.java
[HOPSWORKS-263] Write defensive code to ensure TensorFlow specific parameters are never set for a non-TensorFlow job.
> [HOPSWORKS-263]

- hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/server/ZeppelinConfig.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfig.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/kafka/KafkaFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/exception/CryptoPasswordNotFoundException.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/DistributedFsService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/flink/AbstractYarnClusterDescriptor.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkYarnRunnerBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/tensorflow/TensorFlowYarnRunnerBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnRunner.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/user/CertificateMaterializer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/BaseHadoopClientsService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/HopsUtils.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/yarn/YarnClientService.java
* Write crypto material password to a file in transient dir
* Fix bug with project generic user trying to access hdfs
* Add crypto material file as local resource for jobs launched from job ui. Small fix for YarnClientService regarding users
* Get crypto material password from CertificateMaterializer instead of going to DB again
* Add file with certificates password as LocalResource only when RPC TLS is disabled, otherwise it is injected by the NodeManager
* Fix bug with crypto material password when RPC TLS is disabled
* Materialize certificates passwd file for Zeppelin and Jupyter
* Add double quotes for Jupyter conf
* Change CertificateMaterializer#getUserMaterial to throw an exception instead of returning null in case of missing crypto material for a user …
> HOPSWORKS-290

- hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/notebook/repo/HDFSNotebookRepo.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/rest/NotebookRestApi.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/socket/NotebookServer.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/socket/NotebookServerImpl.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/socket/NotebookServerImplFactory.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/user/activity/ActivityFacade.java
- hopsworks-web/yo/app/scripts/controllers/zeppelinCtrl.js
- hopsworks-web/yo/app/views/zeppelinDashboard.html
* Add project generic user as owner of notebook
* Allow every member to move notes to Trash but only the Data Owner can empty the Trash
* Log activity of moving Notebooks to Zeppelin Trash
* Change Zeppelin Empty trash icon :)
* Zeppelin UI handles the error message. Hopsworks should handle it somehow...
* Handle error message in Hopsworks UI
* Change log severity for exception thrown when user does not have permissions to empty the Trash bin
> HOPSWORKS-329

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/pythonDeps/PythonDepJson.java
- hopsworks-web/yo/Gruntfile.js
- hopsworks-web/yo/app/scripts/controllers/pythonDepsCtrl.js
- hopsworks-web/yo/app/views/projectSettings.html
- hopsworks-web/yo/bower.json
This also fixes the problem with angular-smart-table.js disappearing, by removing the Grunt task 'wiredep'.
https://hopshadoop.atlassian.net/browse/HOPSWORKS-382
> HOPSWORKS-382 - conda channel support

- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/CertificateMaterializer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/HopsUtils.java
Remove certificate password file from HDFS when doing cleanup for Zeppelin and Jupyter
https://hopshadoop.atlassian.net/browse/HOPSWORKS-396
> [HOPSWORKS-396]  

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfig.java
- hopsworks-common/src/main/resources/io/hops/jupyter/config_template.json
do not retry failed TensorFlow tasks, resulting in faster feedback when TensorFlow code fails
> HOPSWORKS-405 do not retry failed TensorFlow tasks

- hopsworks-common/src/main/resources/io/hops/jupyter/config_template.json
- hopsworks-common/src/main/resources/io/hops/jupyter/jupyter_notebook_config_template.py
If log level is set to DEBUG, then Livy server running on the driver cannot serialize the message. The problem exists for Jackson databind library > 2.2.4
> [HOPSWORKS-333]  Configure logging for libhdfs Java upcalls

- hopsworks-web/yo/app/views/jupyterDashboard.html
[HOPSWORKS-413-UI_fix]  Use title instead of placeholder since Firefox has a bug and does not render the new line symbol
Firefox has a bug (https://bugzilla.mozilla.org/show_bug.cgi?id=1391044) and does not render the new line symbol for placeholder in textarea element, although it should according to the specification. Using title instead.
> [HOPSWORKS-413-UI_fix] Use title instead of placeholder for extra Spark properties in Jupyter

- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/CertificateMaterializerAdmin.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/dto/MaterializerStateResponse.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/JupyterService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/rest/InterpreterRestApi.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/rest/NotebookRestApi.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/socket/NotebookServer.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/socket/NotebookServerImpl.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/kafka/KafkaFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/AsynchronousJobExecutor.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/AcquireLockException.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/BaseHadoopClientsService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/CertificateMaterializer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/RemoteMaterialReferencesFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/dao/RemoteMaterialRefID.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/dao/RemoteMaterialReferences.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/HopsUtils.java
- hopsworks-common/src/main/resources/META-INF/persistence.xml
[HOPSWORKS-438]  Materialization in the local filesystem
[HOPSWORKS-438]  Fix synchronization and file removal bug
[HOPSWORKS-438]  Materialize certificates on HDFS
[HOPSWORKS-438]  Remove sync from HDFS
[HOPSWORKS-438]  Implement row exclusive locking for remote material references
[HOPSWORKS-438]  Cleanup code
[HOPSWORKS-438]  Refactor it a little bit
[HOPSWORKS-438]  Replace old CertificateMaterializer
[HOPSWORKS-438]  Fix bugs with persisting to the DB
[HOPSWORKS-438]  Get Materializer state for local certificates
[HOPSWORKS-438]  Get state of the Materializer and fix bug when cancelling removal
[HOPSWORKS-438]  CertificateMaterializer service admin to force remove material
[HOPSWORKS-438]  Fix bug with infinite loop when trying to delete remote material that does not exist …
> [HOPSWORKS-438]  Materialize certificates locally

- hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/JupyterService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterProcessMgr.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/HopsUtils.java
Materialize Jupyter certificates in a custom directoryry, in Project's secret dir
[HOPSWORKS-420]  Pass certificates directory to start Jupyter bash script
[HOPSWORKS-420]  Materialize certificates also in the standard directory so Livy can pick them up
[HOPSWORKS-420]  Put back release version of Hops
https://hopshadoop.atlassian.net/browse/HOPSWORKS-420
Certificates used in Jupyter are now materialized in Jupyter Project's secret directory.
'jupyter' user will no longer be in 'certs' group, thus not able to read other users' …
> [HOPSWORKS-420]  Materialize Jupyter certificates in a custom directory

- hopsworks-api/src/main/java/io/hops/hopsworks/api/hopssite/dto/LocalDatasetHelper.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/DistributedFileSystemOps.java
Use quota cached dataset size as a fast approximation of the dataset's size. When requiring the size of many possibly large datasets getting the real dataset can be very slow. See dela - cluster-published datasets.
> HOPSWORKS-462

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/JupyterSettings.java
HOPSWORKS-382 changed the default values to 0 the number of parameter servers and mpi processes, meaning that default configuration was not a runnable configuration. (Can't run horovod with 0 processes or TFoS with 0 parameter servers)
> HOPSWORKS-459 set correct values for TensorFlowOnSpark and Horovod in JupyterSettings

- hopsworks-admin/src/main/java/io/hops/hopsworks/admin/maintenance/NodesBean.java
- hopsworks-admin/src/main/webapp/security/protected/admin/hostsManagement.xhtml
- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/SystemAdminService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/agent/AgentResource.java
- hopsworks-ca/src/main/java/io/hops/hopsworks/api/certs/CertSigningService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/command/SystemCommand.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/command/SystemCommandFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/pythonDeps/PythonDepsFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/CertificateMaterializer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/CertificatesMgmService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/PKIUtils.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/ServiceCertificateRotationTimer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
[HOPSWORKS-454]  Add REST endpoint for service certificate rotation
[HOPSWORKS-454]  Going to extend the heartbeat protocol of kagent
[HOPSWORKS-454]  Pull kagent heartbeat protocol changes
[HOPSWORKS-454]  Process system commands in heartbeat and issue service key rotation commands
[HOPSWORKS-454]  Schedule periodic service key rotation
[HOPSWORKS-454]  Add button in admin panel to rotate host keys
[HOPSWORKS-454]  Add argument to script signing service csr
[HOPSWORKS-454]  Decrease validity period only for service certificates and not for Dela
https://hopshadoop.atlassian.net/browse/HOPSWORKS-454
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, …
> [HOPSWORKS-454]  Service certificate rotation

- hopsworks-api/src/main/java/io/hops/hopsworks/api/agent/AgentResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/command/SystemCommand.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/command/SystemCommandFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/pythonDeps/CondaCommands.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/pythonDeps/PythonDep.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/pythonDeps/PythonDepsFacade.java
[HOPSWORKS-461]  Introduce NEW status for kagent commands
[HOPSWORKS-461]  Fix wrong command attribute names
[HOPSWORKS-461] Read NEW Conda commands for heartbeat
[HOPSWORKS-461]  Fix bug with NPE when deleting a project
https://hopshadoop.atlassian.net/browse/HOPSWORKS-461
Improvement
kagent commands for managing Conda environments or system commands are executed out of the heartbeat loop. Once a command is received, it is put in a queue and is executed when the previous command has finished. kagent keeps heartbeating updating …
> [HOPSWORKS-461] Remove the execution of kagent commands from the Heartbeat loop

- hopsworks-api/src/main/java/io/hops/hopsworks/api/agent/AgentResource.java
- hopsworks-ca/src/main/java/io/hops/hopsworks/api/certs/CertSigningService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/CertificatesController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/CertificatesMgmService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/OpensslOperations.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/PKIUtils.java
[HOPSWORKS-489] Revoke certificate when user removed from Project
[HOPSWORKS-489] Revoke members of a project when project is removed
[HOPSWORKS-489] Revoke service rotated certificates
https://hopshadoop.atlassian.net/browse/HOPSWORKS-489
New feature
Users, projects, services certificates that are removed from the system are also revoked. The revocation list is available at $DOMAIN1/docroot/intermediate.crl.pem …
> [HOPSWORKS-489] Revoke removed certificates

- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/ServiceCertificateRotationTimer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
[HOPSWORKS-496] Configure enable/disable of service certificate automatic rotation
https://hopshadoop.atlassian.net/browse/HOPSWORKS-496
Improvement
Configuration option to enable/disable automatic service certificate rotation. Rotation can be done explicitly by the Admin panel
No breaking changes
> [HOPSWORKS-496]  Auto service certificate rotation configuration

- hopsworks-api/src/main/java/io/hops/hopsworks/api/agent/AgentResource.java
- hopsworks-ca/src/main/java/io/hops/hopsworks/api/certs/CertSigningService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/CertificatesMgmService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/ServiceCertificateRotationTimer.java
https://hopshadoop.atlassian.net/browse/HOPSWORKS-502
Bug fix
Command line arguments for csr.py have changed. Also, The REST call towards Hopsworks to rotate the certificate has changed. It includes the command ID, if there is one associated.
Depends on https://github.com/hopshadoop/kagent-chef/pull/35
> [HOPSWORKS-502]  Rename old host certificate based on the command ID

- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/OpensslOperations.java
[HOPSWORKS-515]  Increase Host certificate validity period when rotation is disabled
https://hopshadoop.atlassian.net/browse/HOPSWORKS-515
Bug fix
Increased validity period for Host certificates if automatic rotation is disabled
> [HOPSWORKS-515]  Increase Host certificate validity period

- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnJobsMonitor.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnLogUtil.java
In case of Yarn log aggregation status is TIMEOUT, copy whatever logs are available
https://hopshadoop.atlassian.net/browse/HOPSWORKS-537
Bug fix
Aggregated whatever logs are available when the status is from RM is TIME_OUT. Suffix logs with a warning message.
> [HOPSWORKS-537] Aggregate Yarn logs in TIME_OUT status

- hopsworks-api/src/main/java/io/hops/hopsworks/api/app/ApplicationService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/JupyterService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/rest/InterpreterRestApi.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/rest/NotebookRestApi.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/server/ZeppelinConfig.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/socket/NotebookServerImpl.java
- hopsworks-ca/src/main/java/io/hops/hopsworks/api/certs/CertSigningService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/flink/AbstractYarnClusterDescriptor.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/jobhistory/JobState.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkYarnRunnerBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnRunner.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/CertificateMaterializer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/CertificatesController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/CertificatesMgmService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/OpensslOperations.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/HopsUtils.java
[HOPSWORKS-542]  Add REST endpoint for revoking application certificates and refactor signing csr
[HOPSWORKS-542]  Comment-out adding crypto material as local resources for Spark
[HOPSWORKS-542]  Remove adding user's crypto material as local resources of a container if Hops RPC TLS is enabled
[HOPSWORKS-542]  Fix bug in Jupyter config generator with Spark local resources list
[HOPSWORKS-542]  Change the authentication mechanism with user submitted keystore
https://hopshadoop.atlassian.net/browse/HOPSWORKS-542
* **Does this PR introduce …
> [HOPSWORKS-542]  Support for per-Yarn application certificates

- hopsworks-api/src/main/java/io/hops/hopsworks/api/hopssite/dto/LocalDatasetHelper.java
- hopsworks-web/yo/app/scripts/controllers/delaclusterDatasetCtrl.js
Temporarily disable dataset set in cluster dataset listing.
This should once again make the listing usable.
Future work - consider immutable datasets and size save in db or mutable datasets with size being recomputed periodically in the db and providing this stale value on listings.
> HOPSWORKS-570

- hopsworks-common/src/main/resources/io/hops/jupyter/kernel_template.json
> [HOPSWORKS-581] Add missing HADOOP_HDFS_HOME variable in kernel_template.json

- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
https://hopshadoop.atlassian.net/browse/HOPSWORKS-610
Bug fix
Log the project to ops_log only assigned a valid inode
Testing: https://github.com/hopshadoop/hops-testing/pull/121
> [HOPSWORKS-610] Log the project to ops_log only assigned a valid inode
