hopshadoop/hopsworks

HopsWorksBackend/pom.xml
HopsWorksBackend/src/main/java/io/hops/annotations/AllowedRoles.java
HopsWorksBackend/src/main/java/io/hops/filters/RequestAuthFilter.java
HopsWorksBackend/src/main/java/io/hops/integration/ThrowableExceptionMapper.java
HopsWorksBackend/src/main/java/io/hops/model/Users.java
HopsWorksBackend/src/main/java/io/hops/model/UsersInterface.java
HopsWorksBackend/src/main/java/io/hops/rest/application/config/ApplicationConfig.java
HopsWorksBackend/src/main/java/io/hops/services/rest/AdminServices.java
HopsWorksBackend/src/main/java/io/hops/services/rest/AuthService.java
HopsWorksBackend/src/main/java/io/hops/services/rest/JsonResponse.java
HopsWorksBackend/src/main/java/io/hops/services/rest/ProjectService.java
HopsWorksBackend/src/main/java/io/hops/services/rest/UserService.java

created user services that allow a user to update their profile.
created a custom annotation that can be used to annotate methods in the project service. This can be used to restrict access to methods that manipulate projects.
the filter is only a test, it checks if a given method in the project services is annotated and prevents access to the method annotated with owner, and allow access to the one annotated with All. It also restricts access to methods that are in project services but are not annotated( this can be replaced by an exception).

added project filter, and services

---

src/main/java/se/kth/hopsworks/zeppelin/notebook/Notebook.java
src/main/java/se/kth/hopsworks/zeppelin/notebook/repo/FSNotebookRepo.java
src/main/java/se/kth/hopsworks/zeppelin/notebook/repo/NDBNotebookRepo.java
src/main/java/se/kth/hopsworks/zeppelin/rest/InterpreterRestApi.java
src/main/java/se/kth/hopsworks/zeppelin/rest/NotebookRestApi.java
src/main/java/se/kth/hopsworks/zeppelin/server/ZeppelinSingleton.java
src/main/java/se/kth/hopsworks/zeppelin/socket/NotebookServer.java
src/main/java/se/kth/hopsworks/zeppelin/socket/ZeppelinEndpointConfig.java
yo/app/scripts/controllers/project.js

access control for notebooks persisted in file is added. It is not fully tested but can create different folders for projects (folder name being project name) and restrict deletion of notes and paragraphs by Data scientists.

added access control for notebook file persist.

---

dev-deploy-frontend.sh
src/main/java/se/kth/bbc/jobs/spark/SparkJobConfiguration.java
src/main/java/se/kth/bbc/jobs/spark/SparkYarnRunnerBuilder.java
src/main/java/se/kth/hopsworks/controller/SparkController.java
src/main/java/se/kth/rest/application/config/ApplicationConfig.java
yo/app/views/spark.html

Adds spark execution parameters to the execution page

Iss#62 spark params

---

src/main/java/se/kth/hopsworks/rest/DataSetService.java
src/main/java/se/kth/hopsworks/rest/UploadService.java
yo/app/scripts/controllers/templateDropdownCtrl.js
yo/app/views/templateDropdown.html

Fixes not being able to move forward if the user hasn't selected a template when they try to upload files

Made template optional in file upload

---

src/main/java/se/kth/hopsworks/controller/ResponseMessages.java
src/main/java/se/kth/hopsworks/rest/DataSetService.java
yo/app/scripts/controllers/datasetsCtrl.js
yo/app/scripts/controllers/templateDropdownCtrl.js
yo/app/scripts/services/DataSetService.js
yo/app/scripts/services/ModalService.js
yo/app/views/datasetsBrowser.html
yo/app/views/templateDropdown.html

Enables the user to pick a file from the file browser and attach a metadata template to it.

finished attach template to specific file

---

yo/app/scripts/controllers/datasetsCtrl.js

Allows for a metadata field to be edited.

plugged in edit meta field. Fixes #80

---

yo/app/index.html
yo/app/scripts/app.js
yo/bower.json

plugged in dragndrop for meta fields

---

yo/app/scripts/controllers/datasetsCtrl.js
yo/app/scripts/controllers/newCardCtrl.js
yo/app/scripts/util.js

Keeps metadata tables in a fixed position during the editing of a template i.e. when the user creates metadata fields, or metadata tables, or hitting the 'save template' button

Iss#82 steady meta tables

---

src/main/java/se/kth/bbc/project/fb/ByteConverter.java
src/main/java/se/kth/bbc/project/fb/Inode.java
src/main/java/se/kth/bbc/project/fb/InodeFacade.java
src/main/java/se/kth/bbc/project/fb/InodeView.java
src/main/java/se/kth/hopsworks/filters/RequestAuthFilter.java
src/main/java/se/kth/hopsworks/rest/DataSetService.java
src/main/java/se/kth/hopsworks/rest/DownloadService.java
src/main/java/se/kth/hopsworks/rest/RequestService.java
src/main/java/se/kth/hopsworks/rest/UploadService.java
src/main/java/se/kth/hopsworks/zeppelin/util/ZeppelinResource.java
yo/app/scripts/controllers/datasetsCtrl.js
yo/app/scripts/controllers/selectFileCtrl.js
yo/app/scripts/services/AuthInterceptorService.js
yo/app/scripts/services/DataSetService.js
yo/app/views/datasets.html
yo/app/views/datasetsBrowser.html
yo/app/views/newDataSet.html

Download is implemented using location.href= downloadPath.
** This will replace the page with glassfish error page if the download fails.

Fixes #119

---

yo/app/scripts/controllers/dataSetCreatorCtrl.js
yo/app/scripts/controllers/datasetsCtrl.js
yo/app/scripts/controllers/login.js
yo/app/scripts/controllers/profile.js
yo/app/scripts/controllers/project.js
yo/app/scripts/controllers/projectCreator.js
yo/app/scripts/controllers/recoverCtrl.js
yo/app/scripts/controllers/registration.js
yo/app/scripts/controllers/zeppelinCtrl.js
yo/app/scripts/services/DataSetService.js
yo/app/views/login.html
yo/app/views/newDataSet.html
yo/app/views/profile.html
yo/app/views/projectModal.html
yo/app/views/projectSettingsModal.html
yo/app/views/recover.html
yo/app/views/register.html
yo/app/views/zeppelinDashboard.html

Spinners are added to login, register, recover, new project modal, new ds modal, project setting modal, and zeppelin dashboard.

Fixes #124, spinners added for tasks that can take time to finish

---

sql/hopsworks.sql
sql/rows.sql
src/main/java/se/kth/bbc/lims/Constants.java
src/main/java/se/kth/hopsworks/controller/ResponseMessages.java
src/main/java/se/kth/hopsworks/rest/ElasticService.java
src/main/java/se/kth/hopsworks/util/Ip.java
src/main/java/se/kth/hopsworks/util/LocalhostServices.java
src/main/java/se/kth/rest/application/config/Variables.java
src/main/java/se/kth/rest/application/config/VariablesFacade.java
src/main/resources/META-INF/persistence.xml
src/main/setup/glassfish-resources.xml

This PR is to support automated installation of Elasticsearch with Karamel/Chef. It adds a variables table and the address of the elasticsearch server is added as a row in the variables table during installation. Hopsworks reads that IP for the elastic server before sending search requests there.

Elastic config

---

yo/app/scripts/controllers/login.js
yo/app/scripts/controllers/newFieldCtrl.js
yo/app/views/datasets.html
yo/app/views/metadata/newFieldModal.html

Frontend txtresize dev

---

src/main/java/se/kth/bbc/lims/Constants.java
src/main/java/se/kth/hopsworks/meta/db/MetadataFacade.java
src/main/java/se/kth/hopsworks/meta/wscomm/Protocol.java
src/main/java/se/kth/hopsworks/meta/wscomm/Utils.java
src/main/java/se/kth/hopsworks/meta/wscomm/message/Command.java
src/main/java/se/kth/hopsworks/meta/wscomm/message/RemoveMetadataMessage.java
yo/app/scripts/controllers/metadataCtrl.js
yo/app/scripts/services/MetadataActionService.js
yo/app/scripts/services/MetadataService.js
yo/app/views/datasetsBrowser.html

Please test the changes and merge to develop.

Metadata editor changes merge to develop

---

src/main/java/se/kth/bbc/lims/Constants.java
src/main/java/se/kth/bbc/project/NewProjectNameValidator.java
src/main/java/se/kth/hopsworks/controller/FolderNameValidator.java
yo/app/scripts/controllers/projectCreator.js
yo/app/views/projectModal.html

Make sure that the project name does not contain consecutive underscores

Check validity

---

src/main/java/se/kth/bbc/fileoperations/FileSystemOperations.java
src/main/java/se/kth/bbc/project/fb/Inode.java
src/main/java/se/kth/bbc/project/fb/InodeView.java
src/main/java/se/kth/hopsworks/hdfsUsers/HdfsGroupsFacade.java
src/main/java/se/kth/hopsworks/hdfsUsers/HdfsUsersFacade.java
src/main/java/se/kth/hopsworks/hdfsUsers/controller/HdfsUsersController.java
src/main/java/se/kth/hopsworks/hdfsUsers/model/HdfsGroups.java
src/main/java/se/kth/hopsworks/hdfsUsers/model/HdfsUsers.java
src/main/resources/META-INF/persistence.xml
yo/app/views/datasets.html
yo/app/views/datasetsBrowser.html

Still needs work such as making the permissions more readable but all the functionality is there.

Added the metadata details to datasets

---

src/main/java/se/kth/hopsworks/controller/UsersController.java
src/main/webapp/security/login_issue.xhtml
src/main/webapp/security/mobile_recovery.xhtml
src/main/webapp/security/password_changed.xhtml
src/main/webapp/security/password_sent.xhtml
src/main/webapp/security/profile_password_changed.xhtml
src/main/webapp/security/protected/admin/profile_password.xhtml
src/main/webapp/security/protected/audit/auditManagement.xhtml
src/main/webapp/security/protected/researcher/change_sec_question.xhtml
src/main/webapp/security/protected/researcher/deactivate_account.xhtml
src/main/webapp/security/protected/researcher/profile.xhtml
src/main/webapp/security/protected/researcher/profile_password.xhtml
src/main/webapp/security/register_mobile.xhtml
src/main/webapp/security/register_yubico.xhtml
src/main/webapp/security/reset.xhtml
src/main/webapp/security/reset_password.xhtml
src/main/webapp/security/sec_question.xhtml
src/main/webapp/security/sec_question_changed.xhtml
src/main/webapp/security/tos.xhtml
src/main/webapp/security/user_guides.xhtml
src/main/webapp/security/validate_account.xhtml
src/main/webapp/security/validate_code.xhtml
src/main/webapp/security/yubikey_recovery.xhtml
yo/app/views/register.html

Some pages for account recovery and user registration were broken in the develop branch.

Hops consents

---

yo/app/views/datasets.html
yo/app/views/datasetsBrowser.html

Added a metadata button on datasets and an icon in the datasetsBrowser

Metadata icons added

---

src/main/java/se/kth/hopsworks/rest/UploadService.java

Sorry it was my bad that the download was broken. Now it is fixed

Download Fixed by checking permission one time only

---

src/main/java/se/kth/bbc/security/audit/AuditManager.java
src/main/java/se/kth/bbc/security/audit/AuditTrails.java
src/main/java/se/kth/bbc/security/audit/AuditUtil.java
src/main/java/se/kth/bbc/security/audit/RolesAuditActions.java
src/main/java/se/kth/bbc/security/audit/UserAuditActions.java
src/main/java/se/kth/bbc/security/auth/CustomAuthentication.java
src/main/java/se/kth/bbc/security/ua/AccountVerification.java
src/main/java/se/kth/bbc/security/ua/AdminProfileAdministration.java
src/main/java/se/kth/bbc/security/ua/PeopleAdministration.java
src/main/java/se/kth/bbc/security/ua/ProfileManager.java
src/main/java/se/kth/bbc/security/ua/RecoverySelector.java
src/main/java/se/kth/bbc/security/ua/ResetPassword.java
src/main/java/se/kth/bbc/security/ua/authz/RoleEnforcementPoint.java
src/main/java/se/kth/hopsworks/controller/UsersController.java
src/main/java/se/kth/hopsworks/rest/AuthService.java

These audit reports in admin gui work fine now:
- account audit reports
- login report audits
- role audit reports
- project audit reports

audit bugfixes

---

src/main/java/se/kth/bbc/security/auth/CustomAuthentication.java
src/main/java/se/kth/hopsworks/rest/AuthService.java

Made more checks for the Yubikey auth in old and new Yubikey authentication

Yubikey authentication fixes

---

yo/app/views/projectSettingsModal.html

Data retention update fix

---

src/main/java/se/kth/bbc/security/ua/RecoverySelector.java
src/main/java/se/kth/bbc/security/ua/SecurityUtils.java
src/main/java/se/kth/bbc/security/ua/UserRegistration.java
src/main/java/se/kth/hopsworks/controller/UsersController.java
src/main/java/se/kth/hopsworks/rest/AuthService.java

I changed the random generator to:
SecureRandom sha1Prng = SecureRandom.getInstance("SHA1PRNG");
Thought I have not tested it to create new QR codes yet but it should be fine.

Made the OTP secret to use SHA1PRNG in secure random

---

src/main/java/se/kth/bbc/jobs/AsynchronousJobExecutor.java
src/main/java/se/kth/bbc/jobs/execution/HopsJob.java
src/main/java/se/kth/bbc/jobs/spark/SparkJob.java
src/main/java/se/kth/bbc/jobs/spark/SparkYarnRunnerBuilder.java
src/main/java/se/kth/bbc/jobs/yarn/YarnJob.java
src/main/java/se/kth/bbc/jobs/yarn/YarnRunner.java
src/main/java/se/kth/bbc/project/ProjectTeam.java
src/main/java/se/kth/bbc/project/fb/InodeFacade.java
src/main/java/se/kth/hopsworks/controller/DatasetController.java
src/main/java/se/kth/hopsworks/controller/ProjectController.java
src/main/java/se/kth/hopsworks/controller/SparkController.java
src/main/java/se/kth/hopsworks/hdfs/fileoperations/DFSSingleton.java
src/main/java/se/kth/hopsworks/hdfs/fileoperations/DistributedFileSystemOps.java
src/main/java/se/kth/hopsworks/hdfsUsers/controller/HdfsUsersController.java
src/main/java/se/kth/hopsworks/rest/DataSetService.java
src/main/java/se/kth/hopsworks/rest/SparkService.java
src/main/java/se/kth/hopsworks/rest/UploadService.java
src/main/java/se/kth/hopsworks/util/ConfigFileGenerator.java

it should work now the only things that need to be done are :
do some cleaning-up after yarn and
change spark --num-executors to  with --properties-file

Yarn do as

---

pom.xml
scripts/deploy-remote.sh
yo/app/index.html
yo/app/nav.html
yo/app/scripts/app.js
yo/app/scripts/controllers/main.js
yo/app/styles/nav.css
yo/app/styles/style.css
yo/app/views/home.html
yo/bower.json
yo/nbproject/project.properties
yo/nbproject/project.xml
yo/test/karma.conf.js

Public datasets

---

src/main/webapp/WEB-INF/web.xml
yo/app/scripts/services/MetadataService.js
yo/app/scripts/util.js

This is better than hard coding wss 
now it just uses wss iff https is used

Ssl support

---

src/main/java/se/kth/bbc/security/ua/UserAccountsEmailMessages.java
src/main/webapp/security/login_issue.xhtml
yo/app/views/login.html

This PR recovers the login recovery page. It also adds a link to a web support forum on the login page.

Recovered the login recover page and added link to support page

---

src/main/java/se/kth/bbc/security/ua/AdminProfileAdministration.java
src/main/java/se/kth/bbc/security/ua/PeopleAccountStatus.java
src/main/java/se/kth/bbc/security/ua/PeopleAdministration.java
src/main/java/se/kth/bbc/security/ua/ResetPassword.java
src/main/java/se/kth/bbc/security/ua/YubikeyActivator.java
src/main/webapp/security/protected/admin/admin_profile.xhtml

Fixed password recovery and setting maxNumProjs in Admin UI.

Fixed password recovery and setting maxNumProjs in Admin UI

---

src/main/java/se/kth/bbc/jobs/model/description/JobDescriptionFacade.java
src/main/java/se/kth/bbc/project/ProjectsManagementController.java
src/main/java/se/kth/hopsworks/controller/ProjectController.java
src/main/java/se/kth/hopsworks/controller/ProjectDTO.java
src/main/java/se/kth/hopsworks/controller/QuotasDTO.java
src/main/java/se/kth/hopsworks/rest/JobService.java
src/main/java/se/kth/hopsworks/rest/ProjectService.java
src/main/webapp/security/qrcode.xhtml
yo/app/index.html
yo/app/scripts/controllers/jobsCtrl.js
yo/app/scripts/controllers/metadataCtrl.js
yo/app/scripts/controllers/project.js
yo/app/scripts/controllers/projectSettings.js
yo/app/scripts/services/BiobankingService.js
yo/app/scripts/services/ModalService.js
yo/app/scripts/services/ProjectService.js
yo/app/views/metadata.html
yo/app/views/projectSettingsModal.html

This PR reduces the latency for gettings the hdfs and yarn quotas, by introducing a new ProjectSettingsCtrl. It also fixes a bug in deleting jobs.

Quotas now handled by ProjectSettingsCtrl, faster

---

src/main/java/se/kth/bbc/security/ua/AccountVerification.java
src/main/java/se/kth/bbc/security/ua/AdminProfileAdministration.java
src/main/java/se/kth/bbc/security/ua/PeopleAccountStatus.java
src/main/java/se/kth/bbc/security/ua/PeopleAdministration.java
src/main/java/se/kth/bbc/security/ua/RecoverySelector.java
src/main/java/se/kth/bbc/security/ua/ResetPassword.java
src/main/java/se/kth/bbc/security/ua/UserManager.java
src/main/java/se/kth/bbc/security/ua/YubikeyActivator.java
src/main/java/se/kth/bbc/security/ua/authz/RoleEnforcementPoint.java
src/main/java/se/kth/hopsworks/controller/UsersController.java
src/main/java/se/kth/hopsworks/rest/AuthService.java

I reduced the account status for simple user management in the admin GUI.
NB: this is not tested due to the build issue of the cauth realm in Glassfish in the new build system. But as I already pushed my changed to the cauth Realm, these changes are needed to be merged as soon possible to avoid any login issue.
Also since these changes  were mostly re-factoring, I think it should be OK without testing but you never know....

Account status improvement

---

src/main/java/se/kth/bbc/jobs/yarn/YarnRunner.java
src/main/java/se/kth/hopsworks/controller/SparkController.java
src/main/java/se/kth/hopsworks/rest/SparkService.java
src/main/java/se/kth/hopsworks/util/Settings.java
yo/Gruntfile.js
yo/app/views/datasets.html
yo/app/views/datasetsBrowser.html

Fixes regression bug with metadata viewer in datasets.

Inspectjar

---

src/main/java/se/kth/bbc/jobs/AsynchronousJobExecutor.java
src/main/java/se/kth/bbc/jobs/jobhistory/JobState.java
src/main/java/se/kth/bbc/jobs/yarn/YarnJob.java
src/main/java/se/kth/bbc/jobs/yarn/YarnLogUtil.java
src/main/java/se/kth/bbc/jobs/yarn/YarnRunner.java
src/main/java/se/kth/hopsworks/hdfs/fileoperations/DistributedFileSystemOps.java
src/main/java/se/kth/hopsworks/hdfs/fileoperations/DistributedFsService.java
src/main/java/se/kth/hopsworks/rest/JobService.java
yo/app/views/jobs.html

Needs
yarn.log-aggregation-enable to be set true
yarn.nodemanager.remote-app-log-dir  if not set logs are aggregated to /tmp/logs

Yarn log aggregation

---

src/main/java/se/kth/bbc/jobs/yarn/YarnJob.java
yo/app/scripts/controllers/createTopicCtrl.js
yo/app/scripts/controllers/home.js
yo/app/scripts/controllers/kafkaCtrl.js
yo/app/scripts/controllers/selectProjectCtrl.js
yo/app/scripts/controllers/viewPublicDatasetCtrl.js
yo/app/scripts/services/ModalService.js
yo/app/views/createTopic.html
yo/app/views/home.html
yo/app/views/kafka.html
yo/app/views/members.html
yo/app/views/projectModal.html

Jim ui fixes

---

pom.xml
scripts/cargo.sh
src/main/java/se/kth/bbc/jobs/quota/YarnProjectsQuotaFacade.java
src/main/java/se/kth/bbc/project/ProjectsManagementBean.java
src/main/java/se/kth/bbc/project/ProjectsManagementController.java
src/main/java/se/kth/hopsworks/controller/ProjectController.java
src/main/java/se/kth/hopsworks/hdfs/fileoperations/DistributedFileSystemOps.java
src/main/java/se/kth/hopsworks/hdfs/fileoperations/DistributedFsService.java
src/main/java/se/kth/hopsworks/hdfs/fileoperations/HdfsInodeAttributes.java
src/main/java/se/kth/hopsworks/hdfs/fileoperations/UserGroupInformationService.java
src/main/java/se/kth/hopsworks/rest/ElasticService.java
src/main/java/se/kth/hopsworks/rest/JobService.java
src/main/java/se/kth/hopsworks/util/Settings.java
src/main/webapp/security/protected/admin/projectsManagement.xhtml
yo/app/scripts/controllers/memberCtrl.js
yo/app/scripts/controllers/project.js
yo/app/scripts/controllers/projectCreator.js
yo/app/views/metadata.html

The PR does the following:
1. Fixes setting of hdfs and yarn quotas in the mgmt UI
2. fixes filtering out own email and agent@hops.io email addresses for project membership.
3. adds support for the cargo plugin to build and deploy to vagrant from maven - cd scripts; ./cargo.sh hostname port adminPort

Jim admin fixes

---

src/main/java/se/kth/bbc/jobs/flink/FlinkYarnRunnerBuilder.java
src/main/java/se/kth/bbc/jobs/spark/SparkYarnRunnerBuilder.java
src/main/java/se/kth/bbc/jobs/yarn/YarnRunner.java

Using ./* was creating some problems in some machines.

correction to use a specific class path for each kind of application

---

src/main/java/se/kth/hopsworks/rest/DownloadService.java

Change download function to close the stream and the file system object when the download is finished.

close file system after download.

---

src/main/java/se/kth/hopsworks/rest/JobService.java
yo/app/scripts/controllers/jobUICtrl.js
yo/app/views/jobUI.html

improve jobUI to go faster and use less memory when getting the jobUI and to avoid error message in the browser.

improve jobUI

---

src/main/java/se/kth/hopsworks/controller/DataSetDTO.java
src/main/java/se/kth/hopsworks/controller/DatasetController.java
src/main/java/se/kth/hopsworks/controller/ProjectController.java
src/main/java/se/kth/hopsworks/hdfsUsers/controller/HdfsUsersController.java
src/main/java/se/kth/hopsworks/rest/DataSetService.java
src/main/java/se/kth/hopsworks/rest/ProjectService.java
src/main/java/se/kth/hopsworks/util/Settings.java
yo/.netbeans.xml
yo/app/index.html
yo/app/scripts/app.js
yo/app/scripts/controllers/dataSetCreatorCtrl.js
yo/app/scripts/controllers/datasetsCtrl.js
yo/app/scripts/controllers/filePreviewCtrl.js
yo/app/styles/angular-resizable.css
yo/app/views/datasets.html
yo/app/views/datasetsBrowser.html
yo/app/views/newDataSet.html
yo/bower.json

Dataset markdown

---

yo/app/index.html
yo/app/nav.html
yo/app/navProject.html
yo/app/scripts/controllers/datasetsCtrl.js
yo/app/scripts/js/hamburger.js
yo/app/styles/nav.css
yo/app/styles/style.css
yo/app/views/datasets.html
yo/app/views/datasetsBrowser.html
yo/app/views/newProject.html
yo/app/views/projectSettingsModal.html
yo/app/views/zeppelinDashboard.html

Also fixes new project and project setting ui

Dataset ui fixes

---

src/main/java/se/kth/bbc/jobs/jobhistory/JobsHistory.java
src/main/java/se/kth/bbc/jobs/jobhistory/JobsHistoryFacade.java
src/main/java/se/kth/bbc/project/fb/Inode.java
src/main/java/se/kth/bbc/project/fb/InodeFacade.java
src/main/java/se/kth/hopsworks/controller/ProjectController.java
src/main/java/se/kth/hopsworks/drelephant/rest/HistoryService.java
src/main/java/se/kth/hopsworks/rest/ProjectService.java

should be merged at the same time as hopshadoop/hopsworks-chef#43

resolve problem with logs not being properly handled in recreated project

---

src/main/java/se/kth/hopsworks/util/ConfigFileGenerator.java
src/main/java/se/kth/hopsworks/util/HopsUtils.java
src/main/java/se/kth/hopsworks/zeppelin/server/ZeppelinConfig.java
src/main/resources/io/hops/zeppelin/zeppelin_env_template.sh

Append TensorFlow env variables in zeppelin_env_template.sh

Zeppelin evn fix

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java

https://hopshadoop.atlassian.net/browse/HOPSWORKS-13

HOPSWORKS-13

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/user/UserService.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/user/UserDTO.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/user/Users.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/user/UsersController.java
hopsworks-web/yo/app/scripts/controllers/home.js
hopsworks-web/yo/app/scripts/controllers/registration.js
hopsworks-web/yo/app/scripts/services/TourService.js
hopsworks-web/yo/app/views/home.html

Show pop-up informing the user for the guided tours, user can opt-out for the pop-up

HOPSWORKS-16

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/JobService.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/kibana/GrafanaProxyServlet.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/rest/InterpreterRestApi.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/server/ZeppelinConfig.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/HopsUtils.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
hopsworks-common/src/main/resources/io/hops/metrics_template.properties
hopsworks-common/src/main/resources/io/hops/zeppelin/interpreter_template.json
hopsworks-common/src/main/resources/io/hops/zeppelin/zeppelin_env_template.sh
hopsworks-web/yo/app/scripts/app.js
hopsworks-web/yo/app/scripts/controllers/jobUICtrl.js
hopsworks-web/yo/app/scripts/controllers/jobsCtrl.js
hopsworks-web/yo/app/scripts/controllers/zeppelinCtrl.js
hopsworks-web/yo/app/scripts/services/JobService.js
hopsworks-web/yo/app/scripts/services/ZeppelinService.js
hopsworks-web/yo/app/views/jobMonitor.html
hopsworks-web/yo/app/views/zeppelinDashboard.html
scripts/gautier-bbc2.sh

JobUI for zeppelin jobs
- this version does not allow users to change the metrics.properties file, this may become possible with the next zeppelin version.
- it is not possible to access the logs in kibana when running livy jobs because of livy limitations.

[HOPSWORKS-14]

---

hopsworks-admin/src/main/java/io/hops/hopsworks/admin/security/ua/RoleEnforcementPoint.java
hopsworks-admin/src/main/webapp/security/protected/admin/adminIndex.xhtml

Also, . Fixed showing msg when new account is in the activated state

disabled some admin ui services (consent mgmt, auditing)

---

hopsworks-admin/src/main/webapp/WEB-INF/glassfish-web.xml
hopsworks-admin/src/main/webapp/WEB-INF/web.xml
hopsworks-admin/src/main/webapp/security/protected/admin/adminIndex.xhtml
hopsworks-admin/src/main/webapp/security/protected/admin/admintitleBar.xhtml
hopsworks-api/src/main/java/io/hops/hopsworks/api/agent/AgentResource.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/SparkService.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/JupyterConfig.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/pythonDeps/PythonDepsService.java
hopsworks-api/src/main/webapp/WEB-INF/web.xml
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/pythonDeps/PythonDepsFacade.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkController.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkJobConfiguration.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/ConfigFileGenerator.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
hopsworks-common/src/main/resources/io/hops/jupyter/custom_template.js
hopsworks-common/src/main/resources/io/hops/jupyter/jupyter_notebook_config_template.py
hopsworks-common/src/main/resources/io/hops/zeppelin/zeppelin_env_template.sh
hopsworks-kmon/src/main/webapp/WEB-INF/glassfish-web.xml
hopsworks-kmon/src/main/webapp/WEB-INF/web.xml
hopsworks-kmon/src/main/webapp/monitor/layout.xhtml
hopsworks-web/src/main/webapp/WEB-INF/glassfish-web.xml
hopsworks-web/src/main/webapp/WEB-INF/web.xml
hopsworks-web/yo/app/scripts/controllers/pythonDepsCtrl.js
hopsworks-web/yo/app/scripts/services/PythonDepsService.js
hopsworks-web/yo/app/views/projectSettings.html

Admin UI fixes

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/user/UserService.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/user/UserDTO.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/user/Users.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/user/UsersController.java
hopsworks-web/yo/app/navProject.html
hopsworks-web/yo/app/scripts/controllers/home.js
hopsworks-web/yo/app/scripts/services/TourService.js
hopsworks-web/yo/app/views/createTopic.html
hopsworks-web/yo/app/views/home.html
hopsworks-web/yo/app/views/jobs.html
hopsworks-web/yo/app/views/kafka.html
hopsworks-web/yo/app/views/newJob.html
hopsworks-web/yo/app/views/schemaCreate.html
scripts/antonis-bbc2-frontend.sh

Add checkbox so that the user can disable and enable the guided tours balloons
HOPSWORKS-16 branch should also be merged in *hopsworks-chef*

Hopsworks 16

---

hopsworks-common/pom.xml
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/WebCommunication.java
hopsworks-kmon/src/main/java/io/hops/hopsworks/kmon/host/HostController.java

Needed because jersey have a dependency on javax rs which is not compatible with the one used by dela.
And we already use javax.ws.rs that comes with javaee everywhere else.    
But needs to be tested before merging. I can not fully test it because I do not know where it is used. If you have time @jimdowling test it and merge.

removed jersey dependency

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/project/DataSetService.java
hopsworks-web/yo/app/scripts/controllers/datasetsCtrl.js
hopsworks-web/yo/app/scripts/controllers/shareDatasetCtrl.js
hopsworks-web/yo/app/scripts/services/DataSetService.js
hopsworks-web/yo/app/scripts/services/ModalService.js
hopsworks-web/yo/app/views/datasets.html
hopsworks-web/yo/app/views/makeEditable.html
hopsworks-web/yo/app/views/shareDataset.html

change the system to make a dataset editable to make it clear that every user having access to it will have edit right.

[HOPSWORKS-31]

---

hopsworks-web/yo/app/scripts/controllers/datasetsCtrl.js
hopsworks-web/yo/app/scripts/controllers/fileUpload.js
hopsworks-web/yo/app/views/fileUpload.html

close uploader when all files succesfully uploaded

[HOPSWORKS-33]

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/project/DataSetService.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/dataset/Dataset.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/dataset/DatasetFacade.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/hdfs/inode/InodeView.java
hopsworks-web/yo/app/scripts/controllers/datasetsCtrl.js
hopsworks-web/yo/app/styles/filebrowser.css
hopsworks-web/yo/app/views/datasets.html

Mark shared datasets and show how many projects it is shared with (in a tooltip).

[HOPSWORKS-32] mark shard dataset

---

hopsworks-admin/src/main/webapp/WEB-INF/glassfish-web.xml
hopsworks-admin/src/main/webapp/WEB-INF/web.xml
hopsworks-api/src/main/java/io/hops/hopsworks/api/project/DataSetService.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/user/AuthService.java
hopsworks-api/src/main/webapp/WEB-INF/glassfish-web.xml
hopsworks-api/src/main/webapp/WEB-INF/web.xml
hopsworks-common/src/main/java/io/hops/hopsworks/common/dataset/DatasetController.java
hopsworks-kmon/src/main/webapp/WEB-INF/glassfish-web.xml
hopsworks-kmon/src/main/webapp/WEB-INF/web.xml
hopsworks-web/src/main/webapp/WEB-INF/web.xml
hopsworks-web/yo/app/scripts/controllers/datasetsCtrl.js
hopsworks-web/yo/app/scripts/controllers/project.js
hopsworks-web/yo/app/scripts/controllers/shareDatasetCtrl.js
hopsworks-web/yo/app/scripts/controllers/zeppelinCtrl.js
hopsworks-web/yo/app/scripts/services/DataSetService.js
hopsworks-web/yo/app/scripts/services/ModalService.js
hopsworks-web/yo/app/styles/filebrowser.css
hopsworks-web/yo/app/views/datasets.html
hopsworks-web/yo/app/views/jobMonitor.html
hopsworks-web/yo/app/views/removeEditable.html

Changes to DataSets browser to make datasets read-only by group members (only changes ownership of the root of the dataset, and doesn't change ownership of existing directories in the dataset).
New icons for datasets in DataSets Browser.

JobUI Visualization Fixes

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/project/DataSetService.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectService.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/dataset/DataSetDTO.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/hdfs/inode/InodeView.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
hopsworks-web/yo/app/scripts/controllers/cardCtrl.js
hopsworks-web/yo/app/scripts/controllers/datasetsCtrl.js
hopsworks-web/yo/app/scripts/controllers/main.js
hopsworks-web/yo/app/scripts/controllers/viewSearchResultCtrl.js
hopsworks-web/yo/app/scripts/services/DataSetService.js
hopsworks-web/yo/app/scripts/services/ProjectService.js
hopsworks-web/yo/app/styles/filebrowser.css
hopsworks-web/yo/app/styles/style.css
hopsworks-web/yo/app/views/datasets.html
hopsworks-web/yo/app/views/datasetsBrowser.html
hopsworks-web/yo/app/views/home.html
hopsworks-web/yo/app/views/metadata/extendedMetadata.html
hopsworks-web/yo/app/views/project.html
hopsworks-web/yo/app/views/search.html
hopsworks-web/yo/app/views/searchResultDetail.html
hopsworks-web/yo/app/views/zeppelinDashboard.html

- show number of projects a dataset is shared with in the dataset info
- show if a dataset is searchable in the dataset info
- correct some css and html errors
- fixes page min-width, close search, and search page blinking
- Makes that when doing a search you can reach result the file by clicking on it.

HOPSWORKS-41 Diverse fixes for the UI

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/JobService.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/configuration/JobConfiguration.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/execution/ExecutionController.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/jobhistory/JobType.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkController.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkJobConfiguration.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkYarnRunnerBuilder.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnRunner.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
hopsworks-web/yo/app/scripts/controllers/jobDetailCtrl.js
hopsworks-web/yo/app/scripts/controllers/jobsCtrl.js
hopsworks-web/yo/app/scripts/controllers/newJobCtrl.js
hopsworks-web/yo/app/views/jobDetails.html
hopsworks-web/yo/app/views/newJob.html

This PR add the ability to run TensorFlowOnSpark via the JobUI of Hopsworks.

HOPSWORKS-26

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/elastic/ElasticService.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
hopsworks-web/yo/app/scripts/controllers/main.js

change the search queries to avoid returning irrelevant result when doing search.

HOPSWORKS-43

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/util/WebCommunication.java

Client instances are expensive to create, provide a simple pooling mechanism

Disable certificate verification for kagent clients

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/elastic/ElasticService.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/ExecutionService.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/JobService.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/elastic/ElasticController.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/elastic/ElasticHit.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/adam/AdamJob.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/execution/ExecutionController.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkJob.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkYarnRunnerBuilder.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnJob.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnRunner.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
hopsworks-web/yo/app/scripts/controllers/jobsCtrl.js
hopsworks-web/yo/app/scripts/controllers/newJobCtrl.js

Added TTL for job logs in elasticsearch. Job logs are deleted from Elasticsearch when job is deleted. Refactored ElasticService.

Improvements in job logs to elasticsearch.

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/exception/mapper/ThrowableExceptionMapper.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/user/AuthService.java
hopsworks-web/yo/app/scripts/services/AuthInterceptorService.js

- Show warning when trying to login and the database is unavailable.
- logout works even when database is unavailable.
- growl showen only when trying to perform an operation that accesses the database. 
- Only tested for database exceptions that occur when there is mysql server failure and/or mysql cluster failure

HOPSWORKS-9

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/LocalhostServices.java

Remove user certificates when removed from project member

HOPSWORKS-54

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/hdfsUser/HdfsGroups.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/hdfsUser/HdfsUsers.java

https://hopshadoop.atlassian.net/browse/HOPSWORKS-56

HOPSWORKS-56

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/hdfsUser/HdfsGroups.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/hdfsUser/HdfsUsers.java

Reverts hopshadoop/hopsworks#554

Revert "HOPSWORKS-56"

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/FlinkService.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/SparkService.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/HopsUtils.java

Disallow special characters in job name.

(HOPSWORKS-57) Disallow special characters in job name.

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/user/UserDTO.java

For the HiveHops HopsAuthenticator we need to enhance the /user/profile api to return also the username.

HOPSWORKS-62: API /user/profile returns the username

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/tensorflow/TensorboardProxyServlet.java
hopsworks-api/src/main/webapp/WEB-INF/web.xml
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/tensorflow/TensorflowFacade.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnRunner.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/EmailBean.java
hopsworks-web/yo/app/scripts/controllers/jobUICtrl.js
hopsworks-web/yo/app/views/jobMonitor.html

https://hopshadoop.atlassian.net/browse/HOPSWORKS-51
Require to run our version of TensorflowOnSpark: https://github.com/hopshadoop/TensorFlowOnSpark

HOPSWORKS-51

---

hopsworks-api/pom.xml
hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/JobService.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jobs/description/AppIdDTO.java
hopsworks-web/yo/app/scripts/controllers/jobUICtrl.js
hopsworks-web/yo/app/scripts/services/JobService.js
hopsworks-web/yo/app/views/jobMonitor.html

https://hopshadoop.atlassian.net/projects/HOPSWORKS/issues/HOPSWORKS-36

HOPSWORKS-36

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/util/WebCommunication.java
hopsworks-kmon/src/main/java/io/hops/hopsworks/kmon/communication/CommunicationController.java
hopsworks-kmon/src/main/java/io/hops/hopsworks/kmon/service/ServiceInstancesController.java
hopsworks-kmon/src/main/webapp/monitor/service-instances.xhtml

https://hopshadoop.atlassian.net/browse/HOPSWORKS-67

HOPSWORKS-67

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/rest/InterpreterService.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java

HOPSWORKS-65

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/kibana/GrafanaProxyServlet.java
hopsworks-api/src/main/webapp/WEB-INF/web.xml
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/role/Role.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/role/RoleEJB.java
hopsworks-kmon/src/main/java/io/hops/hopsworks/kmon/cluster/ClustersController.java
hopsworks-kmon/src/main/webapp/monitor/clusters.xhtml
hopsworks-kmon/src/main/webapp/monitor/service-instances.xhtml
hopsworks-kmon/src/main/webapp/monitor/service-status.xhtml

add a dashboard for the admin to see the status of the cluster.
https://hopshadoop.atlassian.net/browse/HOPSWORKS-74

Hopsworks-74

---

hopsworks-web/yo/app/scripts/controllers/home.js
hopsworks-web/yo/app/scripts/controllers/project.js

Fix bug with location url
https://hopshadoop.atlassian.net/browse/HOPSWORKS-83

HOPSWORKS-83

---

hopsworks-api/pom.xml
pom.xml

Remove Snapshot version from portal.applications artifacts and disable Apache snapshot maven repository

HOPSWORKS-92

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/JobService.java

changed the influxdb query to match the new structure of data in influxdb introduced in HOPSWORKS-35
https://hopshadoop.atlassian.net/projects/HOPSWORKS/issues/HOPSWORKS-107

HOPSWORKS-107

---

hopsworks-kmon/src/main/java/io/hops/hopsworks/kmon/service/ServiceInstancesController.java
hopsworks-kmon/src/main/webapp/WEB-INF/web.xml
hopsworks-kmon/src/main/webapp/monitor/service-status.xhtml

change SESSION cookie to SESSION-KMON to avoid interferences with the api cookie
don't display grafana when empty
https://hopshadoop.atlassian.net/browse/HOPSWORKS-114

HOPSWORKS-114

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java

change inconsistency checking in project creation to not do clean up when the inconsistency can be volunteer and give more info in the logs
https://hopshadoop.atlassian.net/browse/HOPSWORKS-96

HOPSWORKS-96

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/FlinkService.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/project/DataSetService.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/adam/AdamController.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/adam/AdamJob.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/erasureCode/ErasureCodeJob.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/execution/HopsJob.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/flink/FlinkController.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/flink/FlinkJob.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/flink/FlinkYarnRunnerBuilder.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkController.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkJob.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/tensorflow/TensorFlowController.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/tensorflow/TensorFlowJob.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/tensorflow/TensorFlowYarnRunnerBuilder.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnJob.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/HopsUtils.java
hopsworks-web/yo/app/scripts/controllers/datasetsCtrl.js
hopsworks-web/yo/app/scripts/services/TourService.js
hopsworks-web/yo/app/views/datasetsBrowser.html
hopsworks-web/yo/app/views/newJob.html

* Remote IP from HDFS URI
*Remove NN ip for Tf jobs and put 'default' instead
* Remove 'default' from hdfs path in clipboard
* Add required 'default' for Tf jobs
* Remove NN endpoint from Tours
* Remove default placeholder
https://hopshadoop.atlassian.net/browse/HOPSWORKS-120

HOPSWORKS-120

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/kibana/KibanaProxyServlet.java
hopsworks-web/yo/app/scripts/controllers/jobUICtrl.js
hopsworks-web/yo/app/views/jobMonitor.html

Removed other projects from kibana ui. Removed appId selector from Livy job monitor UI.

[HOPSWORKS-137] 

---

hopsworks-web/yo/app/views/datasetsBrowser.html

Fix file preview bug
https://hopshadoop.atlassian.net/browse/HOPSWORKS-144

HOPSWORKS-144

---

hopsworks-web/yo/app/scripts/controllers/jupyterCtrl.js

Changed jupyterCtrl.js to use relative, not full paths. 
Opening new tab for jupyter when clicked.

fixing reverse proxy problem [HOPSWORKS-78]

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/app/ApplicationService.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/project/CertService.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/server/ZeppelinConfig.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/server/ZeppelinConfigFactory.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/flink/FlinkYarnRunnerBuilder.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkYarnRunnerBuilder.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
hopsworks-common/src/main/resources/io/hops/zeppelin/interpreter_template.json

Add properties for HopsUtil, add endpoint in ApplicationService.

HOPSWORKS-149

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java

Validate against CN instead of keystore alias
https://hopshadoop.atlassian.net/browse/HOPSWORKS-164

HOPSWORKS-164

---

hopsworks-admin/src/main/webapp/security/protected/admin/adminIndex.xhtml
hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/HDFSUIProxyServlet.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/YarnUIProxyServlet.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/kibana/ProxyServlet.java
hopsworks-api/src/main/webapp/WEB-INF/web.xml
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
hopsworks-kmon/src/main/java/io/hops/hopsworks/kmon/service/ServiceInstancesController.java
hopsworks-kmon/src/main/webapp/monitor/service-status.xhtml

Merge at the same time as hopshadoop/hopsworks-chef#79

[HOPSWORKS-165] admin can access HDFS and Yarn UI

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java

Fix bug when adding new member to a project
https://hopshadoop.atlassian.net/browse/HOPSWORKS-172

HOPSWORKS-172

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java

Reverts hopshadoop/hopsworks#624
Breaks Hopsworks until HOPS-68 is merged

Revert "HOPSWORKS-172"

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnJobsMonitor.java

Fix jobs monitoring where application ID was not yet available
https://hopshadoop.atlassian.net/projects/HOPSWORKS/issues/HOPSWORKS-177

HOPSWORKS-177

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/YarnUIProxyServlet.java

Change YARNUIProxyServlet to overwrite urls in html embeded javascript to have them pointing to the proxy servlet and handle pull requests.

[HOPSWORKS-178] 

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/kafka/KafkaFacade.java

Use unique per user password for crypto material
https://hopshadoop.atlassian.net/browse/HOPSWORKS-186

HOPSWORKS-186

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/server/ZeppelinConfig.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/server/ZeppelinConfigFactory.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/socket/NotebookServer.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/util/ZeppelinProjectCleaner.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/util/ZeppelinResource.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/ConfigFileGenerator.java
hopsworks-common/src/main/resources/io/hops/zeppelin/interpreter_template.json

Fix the default zeppelin interpreter json and add code that will prevent deployment if interpreter json not valid.

Hopsworks 190

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/dataset/DatasetController.java

https://hopshadoop.atlassian.net/browse/HOPSWORKS-201

[HOPSWORKS-201] Fix logging dataset creation

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectMembersService.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/rest/InterpreterRestApi.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/server/ZeppelinConfigFactory.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jobhistory/Execution.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jobs/description/JobDescriptionFacade.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFactory.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/HdfsUsersController.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java

https://hopshadoop.atlassian.net/browse/HOPSWORKS-207
https://hopshadoop.atlassian.net/browse/HOPSWORKS-209

[HOPSWORKS-207] and [HOPSWORKS-209]

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java

bug in launching jobs if you don't install in /srv/hops

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/user/security/audit/AuditManager.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java

Whitelist users from auditing their login

HOPSWORKS-159

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/user/CertificateMaterializer.java

Improve CertificateMaterializer when force remove is called
https://hopshadoop.atlassian.net/browse/HOPSWORKS-220

HOPSWORKS-220

---

hopsworks-common/pom.xml

Update hadoop-client version
https://hopshadoop.atlassian.net/browse/HOPSWORKS-221

HOPSWORKS-221

---

hopsworks-web/yo/app/scripts/controllers/clusterUtilisationCtrl.js

Fix initial colour of cluster utilization bar
https://hopshadoop.atlassian.net/browse/HOPSWORKS-222

HOPSWORKS-222

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnExecutionFinalizer.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnJobsMonitor.java

* Reuse open clients
* Separate copying log files from HDFS from updating the state in the database. Make the former async
* Make copying of logs async and update the state when it is done
* Some refactoring
https://hopshadoop.atlassian.net/browse/HOPSWORKS-223

HOPSWORKS-223

---

hopsworks-web/yo/app/views/jupyterDashboard.html

[HOPSWORKS-228] Remove duplicate GPUs field in Jupyter dashboard

[HOPSWORKS-228] Remove duplicate GPUs field in Jupyter dashboard

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/user/CertificateMaterializer.java

* Check the permissions of the transient certificates directory
* Check for transient certificates directory
https://hopshadoop.atlassian.net/browse/HOPSWORKS-234

HOPSWORKS-234

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkYarnRunnerBuilder.java

Remove stray white-space character from spark staging directory
https://hopshadoop.atlassian.net/browse/HOPSWORKS-241

HOPSWORKS-241

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/util/LivyService.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/rest/ConfigurationsRestApi.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/rest/HeliumService.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/rest/InterpreterRestApi.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/rest/InterpreterService.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/rest/NotebookRepoRestApi.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/rest/NotebookRestApi.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/rest/NotebookService.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/server/ZeppelinConfig.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/server/ZeppelinConfigFactory.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/socket/NotebookServer.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/socket/NotebookServerImpl.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/socket/NotebookServerImplFactory.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/util/ZeppelinProjectCleaner.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/util/ZeppelinResource.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/zeppelin/ZeppelinInterpreterConfs.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/user/CertificateMaterializer.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/HopsUtils.java

https://hopshadoop.atlassian.net/projects/HOPSWORKS/issues/HOPSWORKS-214?filter=myopenissues

HOPSWORKS-214

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/JobService.java

… application logs
https://hopshadoop.atlassian.net/projects/HOPSWORKS/issues/HOPSWORKS-239?filter=allopenissues

[HOPSWORKS-239] change log redirect to open the folder containing the application logs

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/DistributedFsService.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/BaseHadoopClientsService.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/yarn/YarnClientService.java

Fix initialization of BaseHadoopClientsService
https://hopshadoop.atlassian.net/browse/HOPSWORKS-248

HOPSWORKS-248

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java

Fix for jupyter tour to change ownership to correct user, it was checking for the yarn user before.

HOPSWORKS-212

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/project/CertificatesController.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java

* Make certificates generation asynchronous
* Do DB operations at the end to avoid TX timeouts
* Wait for certificate generation when adding a new member in a project
https://hopshadoop.atlassian.net/browse/HOPSWORKS-247

HOPSWORKS-247

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/app/ApplicationService.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/project/CertificatesController.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java

* Get project name from the certificate's CN instead of alias. Refactormethods
* Fix TX attributes
https://hopshadoop.atlassian.net/browse/HOPSWORKS-255

HOPSWORKS-255

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/dataset/DatasetController.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java

* Create project's Logs and Resources with superuser dfs and change ownership/permissions
* Create datasets for enabled services as superuser during project creation and change ownership
* Remove waiting for certificates generation thread to finish when RPC TLS is enabled
https://hopshadoop.atlassian.net/browse/HOPSWORKS-254

HOPSWORKS-254

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterProcessFacade.java

Reverts hopshadoop/hopsworks#706

Revert "Remove hadoop version from Jupyter"

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/JobService.java

[Hopsworks 233] account for changed path for TensorBoard endpoint

[Hopsworks 233] account for changed path for TensorBoard endpoint

---

hopsworks-ca/src/main/java/io/hops/hopsworks/api/certs/CertSigningService.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/PKIUtils.java

These changes are to sign a cluster csr with the hops.site root ca.

ca-cert signing changes

---

hopsworks-ca/src/main/java/io/hops/hopsworks/api/certs/CertSigningService.java

cleanup logging for cert signing

---

hopsworks-admin/src/main/java/io/hops/hopsworks/admin/security/ua/RoleEnforcementPoint.java
hopsworks-admin/src/main/java/io/hops/hopsworks/admin/user/account/AccountVerification.java
hopsworks-admin/src/main/java/io/hops/hopsworks/admin/user/account/RecoverySelector.java
hopsworks-admin/src/main/java/io/hops/hopsworks/admin/user/account/ResetPassword.java
hopsworks-admin/src/main/java/io/hops/hopsworks/admin/user/account/YubikeyActivator.java
hopsworks-admin/src/main/java/io/hops/hopsworks/admin/user/administration/PeopleAdministration.java
hopsworks-admin/src/main/java/io/hops/hopsworks/admin/user/profile/AdminProfileAdministration.java
hopsworks-admin/src/main/webapp/security/protected/admin/userManagement.xhtml
hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/UsersAdmin.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/user/AuthService.java
hopsworks-api/src/main/java/io/hops/hopsworks/rest/application/config/ApplicationConfig.java
hopsworks-cluster/src/main/java/io/hops/hopsworks/cluster/controller/ClusterController.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/AbstractFacade.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jobhistory/YarnAppResultFacade.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/user/RoleAction.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/user/UserFacade.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/user/Users.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/user/security/Yubikey.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/user/security/audit/RolesAuditActions.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/user/security/ua/PeopleAccountStatus.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/user/security/ua/PeopleAccountType.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/user/security/ua/SecurityQuestion.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/user/security/ua/UserAccountsEmailMessages.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/user/security/ua/UserManager.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/user/sshkey/SshkeysFacade.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/elastic/ElasticController.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/user/UserStatusValidator.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/user/UsersController.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java

Need hopshadoop/hopsworks-chef#109
https://hopshadoop.atlassian.net/browse/HOPSWORKS-213

[HOPSWORKS-213] REST API for user administration

---

hopsworks-web/yo/app/scripts/services/ModalService.js

HOPSWORKS-287 add missing function to ModalService.js

HOPSWORKS-287 add missing function to ModalService.js

---

hopsworks-web/yo/app/scripts/controllers/jobsCtrl.js
hopsworks-web/yo/app/scripts/controllers/newJobCtrl.js
hopsworks-web/yo/app/views/jobs.html
hopsworks-web/yo/app/views/newJob.html

* Export file description from UI
* Finally read content of a file
* Importing new job
* Refresh page after successful import of job.
* Error handling
* Rearrange export job button
* Move import to new job
https://hopshadoop.atlassian.net/browse/HOPSWORKS-44

HOPSWORKS-44

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/JupyterSettings.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfig.java
hopsworks-common/src/main/resources/io/hops/jupyter/config_template.json
hopsworks-web/yo/app/scripts/controllers/jupyterCtrl.js
hopsworks-web/yo/app/views/jupyterDashboard.html

HOPSWORKS-273 Improvements to Jupyter UI configuration
This PR includes adding Horovod and fixing several bugs related to configuration options in Jupyter
It depends on database changes in the hopsworks-chef PR with the same name.

HOPSWORKS-273 Improvements to Jupyter UI configuration

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/util/DownloadService.java
hopsworks-web/yo/app/scripts/controllers/modalCtrl.js
hopsworks-web/yo/app/scripts/controllers/projectCtrl.js
hopsworks-web/yo/app/scripts/services/DataSetService.js

Reverts hopshadoop/hopsworks#728

Revert "HOPSWORKS-289"

---

hopsworks-web/yo/app/views/newJob.html

Fix broken UI for new jobs
https://hopshadoop.atlassian.net/browse/HOPSWORKS-301

HOPSWORKS-301

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfig.java
hopsworks-common/src/main/resources/io/hops/jupyter/config_template.json
hopsworks-web/yo/app/views/jupyterDashboard.html

HOPSWORKS-271 use dynamic executors instead of static executors for TensorFlow

HOPSWORKS-271 use dynamic executors instead of static executors for TensorFlow

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/project/DataSetService.java

https://hopshadoop.atlassian.net/browse/HOPSWORKS-308

[HOPSWORKS-308] don't write a dataset deletion log while removing a file

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectService.java

Be more defensive in case project or dataset was not found
https://hopshadoop.atlassian.net/browse/HOPSWORKS-311

HOPSWORKS-311

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/util/BaseHadoopClientsService.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/yarn/YarnClientService.java

* Fix project generic user for BaseHadoopClientService

HOPSWORKS-319

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/DistributedFsService.java

Fix bug when closing DFS client for superuser and RPC TLS is enabled

HOPSWORKS-332

---

hopsworks-admin/src/main/java/io/hops/hopsworks/admin/project/ProjectsManagementBean.java
hopsworks-admin/src/main/java/io/hops/hopsworks/admin/project/ProjectsManagementController.java
hopsworks-admin/src/main/webapp/security/protected/admin/projectsManagement.xhtml
hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/ExecutionService.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/JupyterService.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectService.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/socket/NotebookServer.java
hopsworks-common/pom.xml
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jobs/quota/YarnProjectsQuotaFacade.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/project/PaymentType.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/project/Project.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/project/ProjectFacade.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/user/Users.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/user/security/ua/UserManager.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/yarn/containers/YarnContainersLog.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/yarn/containers/YarnContainersLogsFacade.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/ClusterUtil.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
hopsworks-web/yo/app/scripts/controllers/jobsCtrl.js
hopsworks-web/yo/app/scripts/controllers/uberCtrl.js
hopsworks-web/yo/app/scripts/controllers/zeppelinCtrl.js
hopsworks-web/yo/app/scripts/services/ModalService.js
hopsworks-web/yo/app/scripts/services/ProjectService.js
hopsworks-web/yo/app/views/uberModal.html

https://hopshadoop.atlassian.net/projects/HOPSWORKS/issues/HOPSWORKS-312
https://hopshadoop.atlassian.net/projects/HOPSWORKS/issues/HOPSWORKS-315
https://hopshadoop.atlassian.net/projects/HOPSWORKS/issues/HOPSWORKS-316
Needs hopshadoop/hopsworks-chef#116
And needs to be deployed on a machine running HOPS-2.8.2.2-SNAPSHOT or Higher.

 [HOPSWORKS-312],  [HOPSWORKS-315] and  [HOPSWORKS-316]

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/socket/NotebookServer.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/socket/NotebookServerImpl.java

Add project generic user to the connection list mapping
https://hopshadoop.atlassian.net/browse/HOPSWORKS-335

HOPSWORKS-335

---

hopsworks-web/yo/app/scripts/app.js
hopsworks-web/yo/app/views/delahopsDataset.html

Remove custom highlight filter which name collides with the highligh module
https://hopshadoop.atlassian.net/browse/HOPSWORKS-336

HOPSWORKS-336

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfig.java
hopsworks-web/yo/app/views/jupyterDashboard.html

HOPSWORKS-338 remove virtual cores option when configuring TensorFlow in Jupyter

HOPSWORKS-338 remove virtual cores option when configuring TensorFlow in Jupyter

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/user/Users.java

https://hopshadoop.atlassian.net/browse/HOPSWORKS-344

[HOPSWORKS-344] do not persist numCreatedProjects if it is null.

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/user/security/ua/UserManager.java

https://hopshadoop.atlassian.net/browse/HOPSWORKS-348

[HOPSWORKS-348] search spam account with the correct query name

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/elastic/ElasticService.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/elastic/ElasticController.java
hopsworks-web/yo/app/nav.html
hopsworks-web/yo/app/scripts/controllers/datasetsCtrl.js
hopsworks-web/yo/app/scripts/controllers/delaclusterDatasetCtrl.js
hopsworks-web/yo/app/scripts/controllers/delahopsDatasetCtrl.js
hopsworks-web/yo/app/scripts/controllers/mainCtrl.js
hopsworks-web/yo/app/styles/form.css
hopsworks-web/yo/app/styles/search-result.css
hopsworks-web/yo/app/views/datasets.html
hopsworks-web/yo/app/views/datasetsBrowser.html
hopsworks-web/yo/app/views/delaclusterDataset.html
hopsworks-web/yo/app/views/delahopsDataset.html
hopsworks-web/yo/app/views/home.html
hopsworks-web/yo/app/views/project.html
hopsworks-web/yo/app/views/search.html

Does not fix - On startup, it takes 10-20s for the first elasticsearch result. This only happens in a new machine.

HOPSWORKS-196

---

hopsworks-web/yo/app/scripts/controllers/jupyterCtrl.js
hopsworks-web/yo/app/views/jupyterDashboard.html

Fix symbolic link for archives and files, also add jar upload option for TensorFlow

HOPSWORKS-355 Fix symbolic link for archives and files, and add jar

---

scripts/copy.sh

script for js/html development with hopsworks on same machine as IDE

script for js/html development with hopsworks on same machine as IDE

---

hopsworks-web/yo/app/views/jupyterDashboard.html

Fix previously merged HOPSWORKS-338 by removing virtual cores for TFoS also

HOPSWORKS-338 Fix previously merged HOPSWORKS-338 which missed out on TFoS

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/util/ClusterUtilisationService.java
hopsworks-web/yo/app/navProject.html
hopsworks-web/yo/app/scripts/controllers/clusterUtilisationCtrl.js
hopsworks-web/yo/app/scripts/services/ClusterUtilService.js

https://hopshadoop.atlassian.net/browse/HOPSWORKS-360

[HOPSWORKS-360] fix cluster usage indicator.

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/security/CertificatesMgmService.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/security/DelaCertsMasterPasswordHandler.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/security/PGUserCertsMasterPasswordHandler.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/security/PSUserCertsMasterPasswordHandler.java

* Perform rollback for all handlers
* Improve logging
https://hopshadoop.atlassian.net/browse/HOPSWORKS-368

HOPSWORKS-368

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfig.java
hopsworks-web/yo/app/views/jupyterDashboard.html

HOPSWORKS-367 replace executor field with worker in TFoS for Jupyter

HOPSWORKS-367 replace executor field with worker in TFoS for Jupyter

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/kafka/KafkaFacade.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/kafka/TopicAcls.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java

* Delete Kafka ACL when remove a project member
* Filter by project id
https://hopshadoop.atlassian.net/browse/HOPSWORKS-266

HOPSWORKS-266

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/security/CertificatesController.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/security/CertificatesMgmService.java

Exclusive access to bash script for generating certificates
https://hopshadoop.atlassian.net/browse/HOPSWORKS-370

HOPSWORKS-370

---

hopsworks-admin/src/main/java/io/hops/hopsworks/admin/llap/LlapBean.java
hopsworks-admin/src/main/webapp/security/protected/admin/llapManagement.xhtml
hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/llap/LlapAdmin.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/llap/LlapMonitorProxyServlet.java
hopsworks-api/src/main/java/io/hops/hopsworks/rest/application/config/ApplicationConfig.java
hopsworks-api/src/main/webapp/WEB-INF/web.xml
hopsworks-common/src/main/java/io/hops/hopsworks/common/admin/llap/LlapClusterFacade.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/admin/llap/LlapClusterLifecycle.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/admin/llap/LlapClusterStatus.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/constants/message/ResponseMessages.java
hopsworks-web/yo/app/index.html

https://hopshadoop.atlassian.net/projects/HOPSWORKS/issues/HOPSWORKS-359

[HOPSWORKS-359] Add REST endpoint for LLAP cluster admin

---

hopsworks-web/yo/app/navProject.html
hopsworks-web/yo/app/scripts/controllers/clusterUtilisationCtrl.js

https://hopshadoop.atlassian.net/browse/HOPSWORKS-365

[HOPSWORKS-365] make cluster ustilisation prettier

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfig.java

HOPSWORKS-341 Dynamic executors for TensorFlowOnSpark

HOPSWORKS-341 Dynamic executors for TensorFlowOnSpark

---

hopsworks-admin/src/main/webapp/WEB-INF/web.xml

use different session name for hopsworks-admin

HOPSWORKS-375 

---

hopsworks-admin/src/main/java/io/hops/hopsworks/admin/project/ProjectsManagementBean.java
hopsworks-admin/src/main/java/io/hops/hopsworks/admin/project/ProjectsManagementController.java
hopsworks-admin/src/main/webapp/security/protected/admin/projectsManagement.xhtml
hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/ProjectsAdmin.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/rest/InterpreterRestApi.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/rest/InterpreterService.java
hopsworks-api/src/main/java/io/hops/hopsworks/rest/application/config/ApplicationConfig.java

* Do the UI stuff
* View of table in projects management does not updategit diff!
* DataTable update
* Spinner looks OK
* REST endpoint to delete project by id
https://hopshadoop.atlassian.net/browse/HOPSWORKS-371

HOPSWORKS-371 DO NOT MERGE YET

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfig.java

HOPSWORKS-376 Run Horovod on dynamic executors so that resources are released automatically after the job is finished

HOPSWORKS-376 Run Horovod on dynamic executors

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/pythonDeps/PythonDepsFacade.java
hopsworks-web/yo/app/views/projectSettings.html

https://hopshadoop.atlassian.net/browse/HOPSWORKS-173

HOPSWORKS-173 - Support for python 3.6

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/ProjectsAdmin.java
scripts/create_project_as_user.py

* REST endpoint to create project as another user
* Python client to create project as another user
* Change to user email instead of username
https://hopshadoop.atlassian.net/browse/HOPSWORKS-386

HOPSWORKS-386

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/rest/InterpreterRestApi.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/rest/NotebookRestApi.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/socket/NotebookServerImpl.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/security/CertificateMaterializer.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/HopsUtils.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java

* Change the model how we materialize certificates for Zeppelin
https://hopshadoop.atlassian.net/browse/HOPSWORKS-387

HOPSWORKS-387

---

hopsworks-admin/src/main/java/io/hops/hopsworks/admin/project/ProjectsManagementBean.java
hopsworks-admin/src/main/java/io/hops/hopsworks/admin/project/ProjectsManagementController.java
hopsworks-admin/src/main/webapp/security/protected/admin/projectForceRemoveDialog.xhtml
hopsworks-admin/src/main/webapp/security/protected/admin/projectsManagement.xhtml
hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/ProjectsAdmin.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/dto/ProjectDeletionLog.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectService.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/dataset/DatasetFacade.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterProcessFacade.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/hive/HiveController.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java

* Force remove of a project
* Add success logger
* Temporary endpoint for testing
* Remove project quotas and Hive database
* Lock project force cleanup and fix bug with Hive force cleanup
* Refactor both forceCleanup and normal cleanup
* Clean Jupyter environment in forceCleanup and remove duplicate removal of Anaconda
* Separate all the steps of a project's clean up when forced
* Move REST endpoint to the correct class
* Refactor logging for force cleanup operations
* Admin UI for force removing a project
* Send message to inbox with status
https://hopshadoop.atlassian.net/browse/HOPSWORKS-380

HOPSWORKS-380

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/CertificateMaterializerAdmin.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/SystemAdminService.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/dto/MaterializerStateResponse.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/filter/NoCacheResponse.java
hopsworks-api/src/main/java/io/hops/hopsworks/rest/application/config/ApplicationConfig.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/security/CertificateMaterializer.java

* [HOPSWORKS-392]  Get CertificateMaterializer state
* [HOPSWORKS-392] Delete material from store
* [HOPSWORKS-392] Add some documentation and logging
https://hopshadoop.atlassian.net/browse/HOPSWORKS-392

HOPSWORKS-392

---

hopsworks-web/yo/app/views/jupyterDashboard.html

Modification, change step to 1, since users should be able to specify any number of memory and not a multiple of the step.

HOPSWORKS-273 Modification, change step to 1

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/JupyterService.java
hopsworks-web/yo/app/scripts/controllers/jupyterCtrl.js

Notification when project run out of credits, and changed unauthorized return code to forbidden so the user is not automatically returned to login page.

HOPSWORKS-393 Notification for Jupyter when project run out of credits

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/server/ZeppelinConfig.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfig.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkYarnRunnerBuilder.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
hopsworks-common/src/main/resources/io/hops/jupyter/config_template.json
hopsworks-common/src/main/resources/io/hops/zeppelin/interpreter_template.json

@robzor92 These exports can now be removed from tflauncher.py
- https://github.com/hopshadoop/hops-util-py/blob/master/hops/tflauncher.py#L33
- https://github.com/hopshadoop/hops-util-py/blob/master/hops/tflauncher.py#L76

HOPSWORKS-397

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/HDFSUIProxyServlet.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/util/CustomSSLProtocolSocketFactory.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java

[HOPS-153]  Use HTTPS with a custom socket factory for the http client
[HOPS-153]  HDFS browser works
[HOPS-153]  Fix broken regex replacements
[HOPS-153]  Remove hardcoded credentials

[HOPS-153] Secure webhdfs

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectService.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/constants/message/ResponseMessages.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/project/ProjectFacade.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/user/UserDTO.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/user/Users.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/user/UsersController.java
hopsworks-ear/test/spec/helpers/project_helper.rb
hopsworks-ear/test/spec/projects_spec.rb
hopsworks-web/yo/app/scripts/controllers/projectCreatorCtrl.js
hopsworks-web/yo/app/views/newProject.html
hopsworks-web/yo/app/views/profile.html

https://hopshadoop.atlassian.net/browse/HOPSWORKS-414
hopshadoop/hops-testing#16

[HOPSWORKS-414] change the way the max project limit is presented to the users.

---

hopsworks-web/yo/app/navProject.html
hopsworks-web/yo/app/scripts/controllers/homeCtrl.js
hopsworks-web/yo/app/views/home.html

No test needed only front-end changes

HOPSWORKS-354

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java

https://github.com/hopshadoop/hops-testing/pull/19

[HOPSWORKS-419]

---

hopsworks-admin/src/main/java/io/hops/hopsworks/admin/user/administration/UserAdministration.java
hopsworks-admin/src/main/java/io/hops/hopsworks/admin/user/profile/AdminProfileAdministration.java
hopsworks-admin/src/main/webapp/security/protected/admin/admin_profile.xhtml
hopsworks-admin/src/main/webapp/security/protected/admin/admintitleBar.xhtml
hopsworks-admin/src/main/webapp/security/protected/admin/mobileUsers.xhtml
hopsworks-admin/src/main/webapp/security/protected/admin/spamUsers.xhtml
hopsworks-admin/src/main/webapp/security/protected/admin/userManagement.xhtml
hopsworks-cluster/src/main/java/io/hops/hopsworks/cluster/controller/ClusterController.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/user/security/audit/AccountAuditFacade.java

- Fix user administration page
- Fix hopsworks-cluster compilation due sto renaming AuditUtils

HOPSWORKS-427

---

.github/pull_request_template.md

https://hopshadoop.atlassian.net/browse/HOPSWORKS-428

[HOPSWORKS-428]  Add pull request template

---

hopsworks-kmon/src/main/java/io/hops/hopsworks/kmon/cluster/ClustersController.java

https://hopshadoop.atlassian.net/browse/HOPSWORKS-433
Bug fix
Testing: https://github.com/hopshadoop/hops-testing/pull/25

Fix namenode metrics collection/visualisation

---

hopsworks-web/yo/app/views/newJob.html

[HOPSWORKS-430](https://hopshadoop.atlassian.net/browse/HOPSWORKS-430)
https://github.com/hopshadoop/hops-testing/pull/24

HOPSWORKS-430

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/app/ApplicationService.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/tensorflow/TfServingService.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/tfserving/TfServing.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/tfserving/config/TfServingProcessMgr.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
hopsworks-ear/test/spec/helpers/project_helper.rb
hopsworks-ear/test/spec/tfserving_spec.rb
hopsworks-web/yo/app/scripts/controllers/tfservingCtrl.js
hopsworks-web/yo/app/views/tfServing.html

HOPSWORKS-436 fixes for TF Serving

HOPSWORKS-436

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/agent/AgentResource.java

https://hopshadoop.atlassian.net/browse/HOPSWORKS-446
Bug fix
No

[HOPSWORKS-446]

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/agent/AgentResource.java

Reverts hopshadoop/hopsworks#864

Revert "[HOPSWORKS-446]"

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/JobService.java

https://hopshadoop.atlassian.net/browse/HOPSWORKS-440
Bug fix
No
I did not manage to reproduce the problem in my test environment and can't test in the exploitation environment where we are encountering the problem so I'm not 100% sure that this is the fix.
hopshadoop/hops-testing#32

[HOPSWORKS-440]

---

hopsworks-kmon/src/main/webapp/monitor/group-status.xhtml

https://hopshadoop.atlassian.net/browse/HOPSWORKS-447
bug fix
No

[HOPSWORKS-447]

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/agent/AgentResource.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/pythonDeps/PythonDepsService.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/pythonDeps/BlockReport.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/pythonDeps/CondaCommands.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/pythonDeps/OpStatus.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/pythonDeps/PythonDep.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/pythonDeps/PythonDepJson.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/pythonDeps/PythonDepsFacade.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/tfserving/config/TfServingProcessMgr.java
hopsworks-ear/test/spec/conda_spec.rb
hopsworks-web/yo/app/scripts/controllers/pythonDepsCtrl.js
hopsworks-web/yo/app/scripts/services/PythonDepsService.js
hopsworks-web/yo/app/views/projectSettings.html

HOPSWORKS-412 pip-support and conda fixes

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/agent/AgentResource.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/command/KagentCommands.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/command/SystemCommand.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/command/SystemCommandFacade.java
hopsworks-common/src/main/resources/META-INF/persistence.xml

[HOPSWORKS-460]  Send new protocol to kagent
[HOPSWORKS-460]  Update with new protocol
[HOPSWORKS-460]  Fix system commands persistance
[HOPSWORKS-460]  Remove testing code
https://hopshadoop.atlassian.net/browse/HOPSWORKS-460
Improvement
Extends kagent heartbeart protocol with system commands in addition to conda.
NOTE: This PR *breaks* the heartbeat protocol. To update kagent you should patch agent.py. The …

[HOPSWORKS-460] Extends kagent heartbeat protocol

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/pythonDeps/PythonDepsService.java
hopsworks-ear/test/spec/conda_spec.rb
hopsworks-ear/test/spec/helpers/conda_helper.rb
hopsworks-ear/test/spec/spec_helper.rb
hopsworks-web/yo/app/scripts/controllers/jupyterCtrl.js
hopsworks-web/yo/app/scripts/controllers/pythonDepsCtrl.js
hopsworks-web/yo/app/scripts/services/PythonDepsService.js
hopsworks-web/yo/app/views/projectSettings.html

HOPSWORKS-457 misc pip fixes

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/execution/HopsJob.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnJob.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/security/CertificateMaterializer.java

[HOPSWORKS-469]  Remove unused split of username and add missing close of DFS client
[HOPSWORKS-469]  Fix bug wiping out password too early
https://hopshadoop.atlassian.net/browse/HOPSWORKS-469
Bug fix
No breaking changes

[HOPSWORKS-469] Fix CertificateMaterializer bug

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/execution/HopsJob.java

See https://github.com/hopshadoop/hopsworks/pull/879

[HOPSWORKS-469-append]  Remove forgotten unused import from PR-879

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/AdamService.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/FlinkService.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/SparkService.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/TensorFlowService.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/project/DataSetService.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/dataset/Dataset.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/dataset/DatasetFacade.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jobs/description/JobFacade.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jobs/description/Jobs.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/exception/JobCreationException.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/JobController.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/execution/HopsJob.java
hopsworks-web/yo/app/scripts/controllers/newJobCtrl.js

https://hopshadoop.atlassian.net/browse/HOPSWORKS-443

HOPSWORKS-443

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkYarnRunnerBuilder.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnRunner.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/HopsUtils.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/templates/ConfigProperty.java
hopsworks-web/yo/app/views/newJob.html

https://hopshadoop.atlassian.net/projects/HOPSWORKS/issues/HOPSWORKS-474

HOPSWORKS-474

---

hopsworks-cluster/src/main/java/io/hops/hopsworks/cluster/controller/ClusterController.java
hopsworks-dela/src/main/java/io/hops/hopsworks/dela/DelaSetupWorker.java
hopsworks-web/yo/app/scripts/controllers/cardCtrl.js
hopsworks-web/yo/app/scripts/controllers/delaclusterDatasetCtrl.js

1. Fix on previous HOPSWORKS-471 - last refactoring commit introduced a bug in the hopsworks cluster module.
2. fix for cardCtrl dataset GoTo - pick correct delaclusterDataset/delahopsDataset view and set the correct dataset id.
3. if consistently failling on intermediate setup steps, after 20 retries, backoff and retry with a larger delay 

HOPSWORKS-472

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/agent/AgentResource.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/host/HostsFacade.java

HOPSWORKS-479 Kagent not reporting number of GPUs on machine correctly

---

hopsworks-api-v2/src/main/java/io/hops/hopsworks/apiV2/projects/DatasetsResource.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/project/DataSetService.java
hopsworks-ca/src/main/java/io/hops/hopsworks/api/certs/CertSigningService.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/security/CertificatesController.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/security/OpensslOperations.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/security/PKIUtils.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/LocalhostServices.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/SystemCommandExecutor.java

[HOPSWORKS-490]  Move creation of users and services certificates to separate EJB
[HOPSWORKS-490]  Move delete users and services certificates to OpensslOperations EJB
[HOPSWORKS-490]  Refactor openssl operations
https://hopshadoop.atlassian.net/browse/HOPSWORKS-490
Refactoring code, preparatory step for HOPSWORKS-489
No breaking changes

[HOPSWORKS-490] Refactor openssl operations

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkYarnRunnerBuilder.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java

HOPSWORKS-491 remove Python.zip and tfspark.zip

---

hopsworks-dela/src/main/java/io/hops/hopsworks/dela/DelaSetupWorker.java

dela fixes
1. bug - timer restart after 0 ms
2. improvement - enforce 1 timer only - use resetTimer - cancel old timer, create new timer
3. improvement - refactor of logs

HOPSWORKS-495

---

hopsworks-common/src/main/resources/io/hops/jupyter/config_template.json

HOPSWORKS-488 enable R kernel in Jupyter

---

hopsworks-admin/src/main/java/io/hops/hopsworks/admin/user/administration/UserAdministration.java
hopsworks-admin/src/main/webapp/security/protected/admin/mobileUsers.xhtml

https://github.com/hopshadoop/hops-testing/pull/61

HOPSWORKS-494

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/dela/DelaService.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/ClientWrapper.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
hopsworks-dela/src/main/java/io/hops/hopsworks/dela/DelaDatasetController.java

1. Improvement - when asking for a Readme file for a hops published dataset, first check if the dataset is present locally and if yes retrieve Readme file from local cluster.
2. Fix - Readme retrieval mechanism was working over http, move over to https(at the moment without checking validity of cert - this path to be public)

HOPSWORKS-498

---

hopsworks-api-v2/src/main/java/io/hops/hopsworks/apiV2/projects/DatasetsResource.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/project/DataSetService.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/hdfs/inode/InodeView.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
hopsworks-ear/test/spec/dataset_spec.rb
hopsworks-ear/test/spec/helpers/dataset_helper.rb
hopsworks-web/yo/app/scripts/controllers/datasetsCtrl.js
hopsworks-web/yo/app/scripts/services/DataSetService.js
hopsworks-web/yo/app/styles/filebrowser.css
hopsworks-web/yo/app/views/datasetsBrowser.html

HOPSWORKS-476 Add zip support for datasets

---

hopsworks-web/yo/app/scripts/controllers/projectCtrl.js

- [X ] Adds tests for the submitted changes (for bug fixes & features)
- [X ] Passes the tests
- [ X] HOPSWORKS JIRA issue has been opened for this PR
https://hopshadoop.atlassian.net/projects/HOPSWORKS/issues/HOPSWORKS-506
Bugfix
Pia returns saved version
no

HOPSWORKS-506 return pia contents correctly on rest call

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/pythonDeps/PythonDepsService.java
hopsworks-web/yo/app/scripts/controllers/pythonDepsCtrl.js
hopsworks-web/yo/app/views/projectSettings.html

HOPSWORKS-484 Anaconda UI fixes

---

pom.xml

https://hopshadoop.atlassian.net/browse/HOPSWORKS-514
Improvement
Upgrade Hops version to 2.8.2.4-SNAPSHOT

[HOPSWORKS-514]  Upgrade Hops dependency version

---

hopsworks-web/yo/app/scripts/controllers/datasetsCtrl.js
hopsworks-web/yo/app/styles/nav.css
hopsworks-web/yo/app/views/datasets.html
hopsworks-web/yo/app/views/datasetsBrowser.html
hopsworks-web/yo/app/views/metadata/extendedMetadata.html

HOPSWORKS-511 UI resizing for metadata browser

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/JobService.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/tensorflow/TensorboardProxyServlet.java
hopsworks-web/yo/app/views/jobMonitor.html

HOPSWORKS-529 TensorBoard refactor

---

hopsworks-admin/src/main/java/io/hops/hopsworks/admin/user/account/RecoverySelector.java
hopsworks-admin/src/main/java/io/hops/hopsworks/admin/user/account/ResetPassword.java
hopsworks-admin/src/main/webapp/WEB-INF/faces-config.xml
hopsworks-admin/src/main/webapp/security/login_issue.xhtml
hopsworks-admin/src/main/webapp/security/mobile_recovery.xhtml
hopsworks-admin/src/main/webapp/security/password_changed.xhtml
hopsworks-admin/src/main/webapp/security/password_sent.xhtml
hopsworks-admin/src/main/webapp/security/profile_password_changed.xhtml
hopsworks-admin/src/main/webapp/security/qrcode.xhtml
hopsworks-admin/src/main/webapp/security/reset.xhtml
hopsworks-admin/src/main/webapp/security/reset_password.xhtml
hopsworks-admin/src/main/webapp/security/sec_question.xhtml
hopsworks-admin/src/main/webapp/security/sec_question_changed.xhtml
hopsworks-admin/src/main/webapp/security/validate_account.xhtml
hopsworks-admin/src/main/webapp/security/validate_code.xhtml
hopsworks-common/src/main/java/io/hops/hopsworks/common/constants/auth/AccountStatusErrorMessages.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/user/AuthController.java

Hopsworks-534

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java

[HOPSWORKS-538] Remove metrics conf from jypyter

---

hopsworks-web/yo/app/scripts/controllers/jobsCtrl.js
hopsworks-web/yo/app/scripts/controllers/newJobCtrl.js
hopsworks-web/yo/app/scripts/controllers/publicDSPanelCtrl.js
hopsworks-web/yo/app/scripts/services/TfServingService.js
hopsworks-web/yo/app/views/newJob.html

HOPSWORKS-539

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
hopsworks-common/src/main/resources/io/hops/jupyter/config_template.json

[HOPSWORKS-531] Fault-tolerant hyperparameter optimization

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/security/CertificateMaterializer.java

Force delete remote material should not acquire the lock
https://hopshadoop.atlassian.net/browse/HOPSWORKS-545
Bug fix
When forcing to remove crypto material from a remote filesystem, we should not try to acquire the lock.

[HOPSWORKS-545]  Force delete remote material should not acquire the lock

---

hopsworks-common/pom.xml

HOPSWORKS-480

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkYarnRunnerBuilder.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
hopsworks-common/src/main/resources/io/hops/jupyter/config_template.json
hopsworks-web/yo/app/scripts/controllers/jupyterCtrl.js
hopsworks-web/yo/app/scripts/controllers/newJobCtrl.js
hopsworks-web/yo/app/views/jupyterConfigModal.html
hopsworks-web/yo/app/views/jupyterDashboard.html

HOPSWORKS-540

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/util/VariablesService.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/util/VersionsDTO.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
hopsworks-web/yo/app/scripts/controllers/projectCtrl.js
hopsworks-web/yo/app/scripts/services/VariablesService.js
hopsworks-web/yo/app/views/projectSettings.html

- [ X] HOPSWORKS JIRA issue has been opened for this PR
- [ X] All commits have been squashed down to a single commit
https://hopshadoop.atlassian.net/projects/HOPSWORKS/issues/HOPSWORKS-554
Feature
You can see the currently installed versions of software in Hopsworks.
No

[HOPSWORKS-554] Versions of software in Hopsworks in projectSettings UI

---

hopsworks-web/yo/app/index.html
hopsworks-web/yo/bower.json

https://hopshadoop.atlassian.net/projects/HOPSWORKS/issues/HOPSWORKS-557

[HOPSWORKS-557] fix typo and /app

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/agent/AgentResource.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/pythonDeps/PythonDepsService.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/host/HostsFacade.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/pythonDeps/CondaCommands.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/pythonDeps/EnvironmentYmlJson.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/pythonDeps/PythonDepsFacade.java
hopsworks-ear/test/spec/conda_spec.rb
hopsworks-web/yo/app/index.html
hopsworks-web/yo/app/scripts/controllers/pythonDepsCtrl.js
hopsworks-web/yo/app/scripts/controllers/selectEnvYmlCtrl.js
hopsworks-web/yo/app/scripts/services/ModalService.js
hopsworks-web/yo/app/scripts/services/PythonDepsService.js
hopsworks-web/yo/app/views/python.html
hopsworks-web/yo/app/views/selectEnvYml.html

[HOPSWORKS-541] Export/create Anaconda environment from .yml

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/JupyterSettings.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
hopsworks-web/yo/app/views/jupyterDashboard.html

HOPSWORKS-569 add option to enable/disable blacklisting

---

hopsworks-ear/test/spec/conda_spec.rb

HOPSWORKS-573 fix tensorflow serving install

---

hopsworks-web/yo/app/views/tfServing.html

[hopsworks-574] ui fix for tf serving

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkYarnRunnerBuilder.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/HopsUtils.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/templates/AppendConfigReplacementPolicy.java

[HOPSWORKS-576](https://hopshadoop.atlassian.net/projects/HOPSWORKS/issues/HOPSWORKS-576)

[HOPSWORKS-576] Append proper delimiter for differrent spark properties.

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectService.java

[HOPSWORKS-590] Add DataScientist role in PIA get endpoint

---

hopsworks-web/yo/app/views/jupyterDashboard.html

[HOPSWORKS-588] Fix Horovod UI bug in Jupyter configuration

---

hopsworks-web/yo/app/scripts/controllers/kafkaCtrl.js

HOPSWORKS-522 fix

---

pom.xml

Test: https://github.com/hopshadoop/hops-testing/pull/114

[HOPSWORKS-597] Update Hops dependency in Hopsworks to 2.8.2.5-snapshot

---

hopsworks-common/src/main/java/io/hops/hopsworks/common/security/OpensslOperations.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java

[HOPSWORKS-613]  Add configuration property for application certificate validity period
[HOPSWORKS-613]  Set validity period for application certificate
https://hopshadoop.atlassian.net/browse/HOPSWORKS-613
New feature
Configurable application certificate validity period

[HOPSWORKS-613]  Add application certificate version in the filename

---

hopsworks-cluster/src/main/java/io/hops/hopsworks/cluster/controller/ClusterController.java
hopsworks-common/src/main/java/io/hops/hopsworks/common/security/PKI.java
hopsworks-ear/test/spec/ca_spec.rb

https://github.com/hopshadoop/hops-testing/pull/125

[HOPSWORKS-617] Hopsworks-579 breaks build with -Pcluster profile

---

hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/HDFSUIProxyServlet.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/YarnUIProxyServlet.java
hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/JobService.java

[Hopsworks-624] ProxyServlet classes do not match properly on upper case letter in urls
